// Package schemas provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package schemas

import (
	"time"
)

const (
	BearerAuthScopes bearerAuthContextKey = "bearerAuth.Scopes"
)

// Defines values for CapabilityTransport.
const (
	Fixture   CapabilityTransport = "fixture"
	Http      CapabilityTransport = "http"
	Sse       CapabilityTransport = "sse"
	Stdio     CapabilityTransport = "stdio"
	Websocket CapabilityTransport = "websocket"
)

// Valid indicates whether the value is a known member of the CapabilityTransport enum.
func (e CapabilityTransport) Valid() bool {
	switch e {
	case Fixture:
		return true
	case Http:
		return true
	case Sse:
		return true
	case Stdio:
		return true
	case Websocket:
		return true
	default:
		return false
	}
}

// Defines values for CapabilityStatus.
const (
	CapabilityStatusBlockedByPolicy CapabilityStatus = "blocked-by-policy"
	CapabilityStatusDegraded        CapabilityStatus = "degraded"
	CapabilityStatusMissing         CapabilityStatus = "missing"
	CapabilityStatusOk              CapabilityStatus = "ok"
	CapabilityStatusUntested        CapabilityStatus = "untested"
)

// Valid indicates whether the value is a known member of the CapabilityStatus enum.
func (e CapabilityStatus) Valid() bool {
	switch e {
	case CapabilityStatusBlockedByPolicy:
		return true
	case CapabilityStatusDegraded:
		return true
	case CapabilityStatusMissing:
		return true
	case CapabilityStatusOk:
		return true
	case CapabilityStatusUntested:
		return true
	default:
		return false
	}
}

// Defines values for HealthResponseAdapters.
const (
	HealthResponseAdaptersDegraded HealthResponseAdapters = "degraded"
	HealthResponseAdaptersMissing  HealthResponseAdapters = "missing"
	HealthResponseAdaptersOk       HealthResponseAdapters = "ok"
	HealthResponseAdaptersUnknown  HealthResponseAdapters = "unknown"
)

// Valid indicates whether the value is a known member of the HealthResponseAdapters enum.
func (e HealthResponseAdapters) Valid() bool {
	switch e {
	case HealthResponseAdaptersDegraded:
		return true
	case HealthResponseAdaptersMissing:
		return true
	case HealthResponseAdaptersOk:
		return true
	case HealthResponseAdaptersUnknown:
		return true
	default:
		return false
	}
}

// Defines values for HealthResponseStatus.
const (
	Degraded HealthResponseStatus = "degraded"
	Draining HealthResponseStatus = "draining"
	Ok       HealthResponseStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthResponseStatus enum.
func (e HealthResponseStatus) Valid() bool {
	switch e {
	case Degraded:
		return true
	case Draining:
		return true
	case Ok:
		return true
	default:
		return false
	}
}

// Defines values for MigrationStatePhase.
const (
	Failed     MigrationStatePhase = "failed"
	Idle       MigrationStatePhase = "idle"
	RolledBack MigrationStatePhase = "rolled_back"
	Running    MigrationStatePhase = "running"
)

// Valid indicates whether the value is a known member of the MigrationStatePhase enum.
func (e MigrationStatePhase) Valid() bool {
	switch e {
	case Failed:
		return true
	case Idle:
		return true
	case RolledBack:
		return true
	case Running:
		return true
	default:
		return false
	}
}

// Defines values for ToolId.
const (
	AgentMail     ToolId = "agent_mail"
	Br            ToolId = "br"
	Bv            ToolId = "bv"
	Caam          ToolId = "caam"
	Casr          ToolId = "casr"
	Caut          ToolId = "caut"
	Dcg           ToolId = "dcg"
	Git           ToolId = "git"
	HealthGeneric ToolId = "health_generic"
	HealthGo      ToolId = "health_go"
	HealthPy      ToolId = "health_py"
	HealthRs      ToolId = "health_rs"
	HealthTs      ToolId = "health_ts"
	Jfp           ToolId = "jfp"
	Jsm           ToolId = "jsm"
	Ntm           ToolId = "ntm"
	Oracle        ToolId = "oracle"
	Pt            ToolId = "pt"
	Rch           ToolId = "rch"
	Ru            ToolId = "ru"
	Sbh           ToolId = "sbh"
	Srp           ToolId = "srp"
	Ubs           ToolId = "ubs"
)

// Valid indicates whether the value is a known member of the ToolId enum.
func (e ToolId) Valid() bool {
	switch e {
	case AgentMail:
		return true
	case Br:
		return true
	case Bv:
		return true
	case Caam:
		return true
	case Casr:
		return true
	case Caut:
		return true
	case Dcg:
		return true
	case Git:
		return true
	case HealthGeneric:
		return true
	case HealthGo:
		return true
	case HealthPy:
		return true
	case HealthRs:
		return true
	case HealthTs:
		return true
	case Jfp:
		return true
	case Jsm:
		return true
	case Ntm:
		return true
	case Oracle:
		return true
	case Pt:
		return true
	case Rch:
		return true
	case Ru:
		return true
	case Sbh:
		return true
	case Srp:
		return true
	case Ubs:
		return true
	default:
		return false
	}
}

// Defines values for VersionResponseDaemonChannel.
const (
	Dev     VersionResponseDaemonChannel = "dev"
	Nightly VersionResponseDaemonChannel = "nightly"
	Stable  VersionResponseDaemonChannel = "stable"
)

// Valid indicates whether the value is a known member of the VersionResponseDaemonChannel enum.
func (e VersionResponseDaemonChannel) Valid() bool {
	switch e {
	case Dev:
		return true
	case Nightly:
		return true
	case Stable:
		return true
	default:
		return false
	}
}

// Capability One capability slot inside a `ToolReport`. The map key is the
// capability ID (e.g., `ntm.sessions.list`); the value is this object.
type Capability struct {
	// Fallback Human-readable fallback strategy when status != `ok`. Example:
	// `"tmux capture last"` for `ntm.panes.stream` missing.
	Fallback *string `json:"fallback,omitempty"`

	// Notes Adapter free-text. Surfaced in Diagnostics. Not redacted at the
	// field name (redaction happens at the audit/log boundary, hp-je1p);
	// do not put secrets here.
	Notes *string `json:"notes,omitempty"`

	// Status - `ok` — capability satisfied a contract test.
	// - `degraded` — works via fallback transport / partial output.
	// - `missing` — tool reports the capability is absent.
	// - `blocked-by-policy` — present but disallowed by config.
	// - `untested` — daemon could not probe in this snapshot; renderer
	//   buckets with `missing` (unavailable) but Diagnostics distinguishes
	//   the two.
	Status CapabilityStatus `json:"status"`

	// Transport Transport actually being used for this capability when applicable.
	Transport *CapabilityTransport `json:"transport,omitempty"`
}

// CapabilityTransport Transport actually being used for this capability when applicable.
type CapabilityTransport string

// CapabilityRegistry Authoritative capability snapshot returned by `/v1/capabilities`. The
// `tools` map is keyed by ToolId so renderer code can do
// `registry.tools.git.capabilities['git.push']` in O(1) without scanning
// an array.
type CapabilityRegistry struct {
	// DaemonApiVersion Cross-reference with `/v1/compatibility.daemonApiVersion`.
	DaemonApiVersion string `json:"daemonApiVersion"`

	// FixturesVersion Dominant fixtures tag for the snapshot. Per-tool tags can diverge
	// (each `ToolReport.fixturesVersion` is authoritative for that tool);
	// this is the most-common tag, used for top-level Diagnostics labels.
	FixturesVersion string `json:"fixturesVersion"`

	// SchemaVersion Monotonically increasing schema version for a persisted shape.
	SchemaVersion SchemaVersion `json:"schemaVersion"`

	// SnapshotAt When this composite was assembled (single timestamp across all tools).
	SnapshotAt time.Time `json:"snapshotAt"`

	// Tools Map of ToolId → ToolReport. OpenAPI cannot fully constrain object
	// keys to a closed enum; the daemon enforces `ToolId` membership at
	// serialization. Missing tools are absent from the map (not present
	// with `null`).
	Tools map[string]ToolReport `json:"tools"`
}

// CapabilityStatus - `ok` — capability satisfied a contract test.
//   - `degraded` — works via fallback transport / partial output.
//   - `missing` — tool reports the capability is absent.
//   - `blocked-by-policy` — present but disallowed by config.
//   - `untested` — daemon could not probe in this snapshot; renderer
//     buckets with `missing` (unavailable) but Diagnostics distinguishes
//     the two.
type CapabilityStatus string

// CompatibilityReport defines model for CompatibilityReport.
type CompatibilityReport struct {
	// Capabilities Authoritative capability snapshot returned by `/v1/capabilities`. The
	// `tools` map is keyed by ToolId so renderer code can do
	// `registry.tools.git.capabilities['git.push']` in O(1) without scanning
	// an array.
	Capabilities CapabilityRegistry `json:"capabilities"`

	// DaemonApiVersion Semver of the OpenAPI contract this daemon implements.
	DaemonApiVersion string `json:"daemonApiVersion"`

	// EventSchemaVersions Per-channel event schemaVersion (channel → schemaVersion int).
	EventSchemaVersions map[string]int `json:"eventSchemaVersions"`

	// MigrationState Structured daemon-migration state (§10.3). The renderer can pick the
	// coarse `phase` enum for chrome state OR the detailed
	// `schemaVersion`/`appliedAt`/`pending` fields for Diagnostics ("schema 7
	// of 9 applied; pending: foo, bar"). Both stay consistent.
	MigrationState MigrationState `json:"migrationState"`

	// MinDesktopVersion Minimum compatible desktop semver. Older desktops are warned.
	MinDesktopVersion string `json:"minDesktopVersion"`

	// SchemaVersion Monotonically increasing schema version for a persisted shape.
	SchemaVersion SchemaVersion `json:"schemaVersion"`

	// UnsupportedClientWarnings Free-form human-readable warnings (e.g., "desktop 0.0.5 below
	// minimum 0.1.0; please update"). Renderer surfaces these in the
	// top-bar.
	UnsupportedClientWarnings *[]string `json:"unsupportedClientWarnings,omitempty"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	// Adapters Coarse per-tool adapter status (cheap; no full capability check).
	// For authoritative capability gating call `/v1/capabilities`.
	Adapters *map[string]HealthResponseAdapters `json:"adapters,omitempty"`

	// DaemonId Stable daemon instance ID; changes on reinstall.
	DaemonId      string               `json:"daemonId"`
	Status        HealthResponseStatus `json:"status"`
	Time          time.Time            `json:"time"`
	UptimeSeconds *int                 `json:"uptimeSeconds,omitempty"`
}

// HealthResponseAdapters defines model for HealthResponse.Adapters.
type HealthResponseAdapters string

// HealthResponseStatus defines model for HealthResponse.Status.
type HealthResponseStatus string

// MigrationState Structured daemon-migration state (§10.3). The renderer can pick the
// coarse `phase` enum for chrome state OR the detailed
// `schemaVersion`/`appliedAt`/`pending` fields for Diagnostics ("schema 7
// of 9 applied; pending: foo, bar"). Both stay consistent.
type MigrationState struct {
	// AppliedAt When the most recent migration step finished.
	AppliedAt time.Time `json:"appliedAt"`

	// Pending Identifiers of unapplied migrations (empty in steady state).
	Pending []string `json:"pending"`

	// Phase Optional coarse phase. Always derivable from the structured fields
	// (`pending == [] → idle` etc.); included so renderer chrome can pick
	// it without computing.
	Phase *MigrationStatePhase `json:"phase,omitempty"`

	// SchemaVersion Currently applied schema version.
	SchemaVersion int `json:"schemaVersion"`
}

// MigrationStatePhase Optional coarse phase. Always derivable from the structured fields
// (`pending == [] → idle` etc.); included so renderer chrome can pick
// it without computing.
type MigrationStatePhase string

// Problem RFC 7807 problem+json. `type` is a daemon-stable URN; `code` is a short
// machine-readable identifier (e.g., `auth.token_expired`,
// `capability.missing`). `instance` is a per-incident URI for support
// deep-links into Diagnostics.
type Problem struct {
	// ApprovalId For `approval.required` problems, the queued approval ID.
	ApprovalId *string `json:"approvalId,omitempty"`

	// Capability For `capability.missing` / `capability.degraded` problems, the
	// capability ID that the operation required.
	Capability *string `json:"capability,omitempty"`

	// Code Machine-readable error code (dot-separated namespace).
	Code string `json:"code"`

	// CorrelationId Opaque correlation handle (matches audit-log entries).
	CorrelationId *string `json:"correlationId,omitempty"`

	// Detail Human-readable explanation; redacted for sensitive fields.
	Detail *string `json:"detail,omitempty"`

	// Instance Per-incident URI; `urn:hoopoe:incident:<id>` is canonical.
	Instance *string `json:"instance,omitempty"`

	// RequestId Echoes `X-Request-Id` if provided.
	RequestId *string `json:"requestId,omitempty"`

	// RetryAfterSeconds Optional hint for `Retry-After`.
	RetryAfterSeconds *int `json:"retryAfterSeconds,omitempty"`

	// Retryable True if the client may safely retry with the same Idempotency-Key.
	Retryable *bool `json:"retryable,omitempty"`

	// Status Mirrors HTTP status.
	Status int `json:"status"`

	// Title Short, human-readable summary.
	Title string `json:"title"`

	// Type Stable problem-type URN (e.g., `urn:hoopoe:auth/token-expired`).
	Type string `json:"type"`
}

// SchemaVersion Monotonically increasing schema version for a persisted shape.
type SchemaVersion = int

// ToolId Closed enum of tools the capability registry knows about. New
// ecosystem health probes (e.g., `health_zig`) require an explicit
// spec bump per §10.3; the daemon-side checker uses a `health_*`
// prefix-match for forward-compat input validation.
type ToolId string

// ToolReport One tool's slice of the capability registry. Compose into
// `CapabilityRegistry.tools` keyed by ToolId.
type ToolReport struct {
	// Capabilities Map of capability ID → capability slot. Capability IDs are dotted
	// namespaces (e.g., `ntm.sessions.list`, `bv.robot.triage`). The full
	// list of recognised capability IDs is owned by hp-r33.
	Capabilities map[string]Capability `json:"capabilities"`

	// FixturesVersion Phase 0 fixture tag this registry was validated against.
	FixturesVersion string    `json:"fixturesVersion"`
	LastCheckedAt   time.Time `json:"lastCheckedAt"`

	// Source How capabilities were detected. Examples: `"ntm serve"`,
	// `"--robot-* JSON"`, `"CLI"`, `"fixture"`.
	Source string `json:"source"`

	// Tool Closed enum of tools the capability registry knows about. New
	// ecosystem health probes (e.g., `health_zig`) require an explicit
	// spec bump per §10.3; the daemon-side checker uses a `health_*`
	// prefix-match for forward-compat input validation.
	Tool ToolId `json:"tool"`

	// Version Semver (or vendor version string) of the tool. Empty if unknown.
	Version string `json:"version"`
}

// VersionResponse defines model for VersionResponse.
type VersionResponse struct {
	Daemon struct {
		AttestationUri *string                       `json:"attestationUri,omitempty"`
		BuildTime      *time.Time                    `json:"buildTime,omitempty"`
		Channel        *VersionResponseDaemonChannel `json:"channel,omitempty"`

		// Checksum Distribution checksum (matches release manifest)
		Checksum *string `json:"checksum,omitempty"`

		// Commit Git SHA of the build
		Commit *string `json:"commit,omitempty"`

		// SbomDigest SBOM digest recorded at install time (§11)
		SbomDigest *string `json:"sbomDigest,omitempty"`

		// SigningIdentity Signer identity (e.g., "Hoopoe v1 Release Key")
		SigningIdentity *string `json:"signingIdentity,omitempty"`

		// Version Semver of the daemon binary
		Version string `json:"version"`
	} `json:"daemon"`

	// SchemaVersion Monotonically increasing schema version for a persisted shape.
	SchemaVersion SchemaVersion `json:"schemaVersion"`
}

// VersionResponseDaemonChannel defines model for VersionResponse.Daemon.Channel.
type VersionResponseDaemonChannel string

// bearerAuthContextKey is the context key for bearerAuth security scheme
type bearerAuthContextKey string

// GetCapabilitiesParams defines parameters for GetCapabilities.
type GetCapabilitiesParams struct {
	// Tool Filter to a single tool (e.g., `ntm`, `br`, `bv`).
	Tool *string `form:"tool,omitempty" json:"tool,omitempty"`
}
