// Package schemas provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package schemas

import (
	"time"
)

const (
	BearerAuthScopes bearerAuthContextKey = "bearerAuth.Scopes"
)

// Defines values for ActionKind.
const (
	AgentAskStatus          ActionKind = "agent.ask_status"
	AgentKillWedgedProcess  ActionKind = "agent.kill_wedged_process"
	AgentPause              ActionKind = "agent.pause"
	AgentSendMarchingOrders ActionKind = "agent.send_marching_orders"
	BeadCreateBlocker       ActionKind = "bead.create_blocker"
	CaamSwitchAccount       ActionKind = "caam.switch_account"
	CasrResumeSession       ActionKind = "casr.resume_session"
	GitPushBranch           ActionKind = "git.push_branch"
	ReservationForceRelease ActionKind = "reservation.force_release"
	ReviewProposeFlip       ActionKind = "review.propose_flip"
	SwarmHalt               ActionKind = "swarm.halt"
)

// Valid indicates whether the value is a known member of the ActionKind enum.
func (e ActionKind) Valid() bool {
	switch e {
	case AgentAskStatus:
		return true
	case AgentKillWedgedProcess:
		return true
	case AgentPause:
		return true
	case AgentSendMarchingOrders:
		return true
	case BeadCreateBlocker:
		return true
	case CaamSwitchAccount:
		return true
	case CasrResumeSession:
		return true
	case GitPushBranch:
		return true
	case ReservationForceRelease:
		return true
	case ReviewProposeFlip:
		return true
	case SwarmHalt:
		return true
	default:
		return false
	}
}

// Defines values for ActorKind.
const (
	ActorKindAgent     ActorKind = "agent"
	ActorKindApproval  ActorKind = "approval"
	ActorKindDcg       ActorKind = "dcg"
	ActorKindScheduler ActorKind = "scheduler"
	ActorKindSystem    ActorKind = "system"
	ActorKindUser      ActorKind = "user"
)

// Valid indicates whether the value is a known member of the ActorKind enum.
func (e ActorKind) Valid() bool {
	switch e {
	case ActorKindAgent:
		return true
	case ActorKindApproval:
		return true
	case ActorKindDcg:
		return true
	case ActorKindScheduler:
		return true
	case ActorKindSystem:
		return true
	case ActorKindUser:
		return true
	default:
		return false
	}
}

// Defines values for ApprovalRiskClass.
const (
	Critical ApprovalRiskClass = "critical"
	High     ApprovalRiskClass = "high"
	Low      ApprovalRiskClass = "low"
	Medium   ApprovalRiskClass = "medium"
)

// Valid indicates whether the value is a known member of the ApprovalRiskClass enum.
func (e ApprovalRiskClass) Valid() bool {
	switch e {
	case Critical:
		return true
	case High:
		return true
	case Low:
		return true
	case Medium:
		return true
	default:
		return false
	}
}

// Defines values for ApprovalScope.
const (
	Once               ApprovalScope = "once"
	ThisBead           ApprovalScope = "this_bead"
	ThisProjectSession ApprovalScope = "this_project_session"
	ThisSwarm          ApprovalScope = "this_swarm"
)

// Valid indicates whether the value is a known member of the ApprovalScope enum.
func (e ApprovalScope) Valid() bool {
	switch e {
	case Once:
		return true
	case ThisBead:
		return true
	case ThisProjectSession:
		return true
	case ThisSwarm:
		return true
	default:
		return false
	}
}

// Defines values for ApprovalSource.
const (
	ApprovalSourceDcg          ApprovalSource = "dcg"
	ApprovalSourceHoopoePolicy ApprovalSource = "hoopoe_policy"
)

// Valid indicates whether the value is a known member of the ApprovalSource enum.
func (e ApprovalSource) Valid() bool {
	switch e {
	case ApprovalSourceDcg:
		return true
	case ApprovalSourceHoopoePolicy:
		return true
	default:
		return false
	}
}

// Defines values for ApprovalState.
const (
	Approved ApprovalState = "approved"
	Denied   ApprovalState = "denied"
	Expired  ApprovalState = "expired"
	Pending  ApprovalState = "pending"
	Revoked  ApprovalState = "revoked"
)

// Valid indicates whether the value is a known member of the ApprovalState enum.
func (e ApprovalState) Valid() bool {
	switch e {
	case Approved:
		return true
	case Denied:
		return true
	case Expired:
		return true
	case Pending:
		return true
	case Revoked:
		return true
	default:
		return false
	}
}

// Defines values for ArtifactRefKind.
const (
	BootstrapLog    ArtifactRefKind = "bootstrap_log"
	ConversionTrace ArtifactRefKind = "conversion_trace"
	HealthSnapshot  ArtifactRefKind = "health_snapshot"
	Log             ArtifactRefKind = "log"
	Misc            ArtifactRefKind = "misc"
	PlanArtifact    ArtifactRefKind = "plan_artifact"
	ReviewFinding   ArtifactRefKind = "review_finding"
)

// Valid indicates whether the value is a known member of the ArtifactRefKind enum.
func (e ArtifactRefKind) Valid() bool {
	switch e {
	case BootstrapLog:
		return true
	case ConversionTrace:
		return true
	case HealthSnapshot:
		return true
	case Log:
		return true
	case Misc:
		return true
	case PlanArtifact:
		return true
	case ReviewFinding:
		return true
	default:
		return false
	}
}

// Defines values for BeadDependencyEdgeDependencyType.
const (
	Blocks  BeadDependencyEdgeDependencyType = "blocks"
	Parent  BeadDependencyEdgeDependencyType = "parent"
	Related BeadDependencyEdgeDependencyType = "related"
)

// Valid indicates whether the value is a known member of the BeadDependencyEdgeDependencyType enum.
func (e BeadDependencyEdgeDependencyType) Valid() bool {
	switch e {
	case Blocks:
		return true
	case Parent:
		return true
	case Related:
		return true
	default:
		return false
	}
}

// Defines values for BeadIssueType.
const (
	Bug      BeadIssueType = "bug"
	Docs     BeadIssueType = "docs"
	Epic     BeadIssueType = "epic"
	Feature  BeadIssueType = "feature"
	Question BeadIssueType = "question"
	Task     BeadIssueType = "task"
)

// Valid indicates whether the value is a known member of the BeadIssueType enum.
func (e BeadIssueType) Valid() bool {
	switch e {
	case Bug:
		return true
	case Docs:
		return true
	case Epic:
		return true
	case Feature:
		return true
	case Question:
		return true
	case Task:
		return true
	default:
		return false
	}
}

// Defines values for BeadStatus.
const (
	Blocked    BeadStatus = "blocked"
	Closed     BeadStatus = "closed"
	Deleted    BeadStatus = "deleted"
	InProgress BeadStatus = "in_progress"
	Open       BeadStatus = "open"
)

// Valid indicates whether the value is a known member of the BeadStatus enum.
func (e BeadStatus) Valid() bool {
	switch e {
	case Blocked:
		return true
	case Closed:
		return true
	case Deleted:
		return true
	case InProgress:
		return true
	case Open:
		return true
	default:
		return false
	}
}

// Defines values for CapabilityTransport.
const (
	Fixture   CapabilityTransport = "fixture"
	Http      CapabilityTransport = "http"
	Sse       CapabilityTransport = "sse"
	Stdio     CapabilityTransport = "stdio"
	Websocket CapabilityTransport = "websocket"
)

// Valid indicates whether the value is a known member of the CapabilityTransport enum.
func (e CapabilityTransport) Valid() bool {
	switch e {
	case Fixture:
		return true
	case Http:
		return true
	case Sse:
		return true
	case Stdio:
		return true
	case Websocket:
		return true
	default:
		return false
	}
}

// Defines values for CapabilityStatus.
const (
	CapabilityStatusBlockedByPolicy CapabilityStatus = "blocked-by-policy"
	CapabilityStatusDegraded        CapabilityStatus = "degraded"
	CapabilityStatusMissing         CapabilityStatus = "missing"
	CapabilityStatusOk              CapabilityStatus = "ok"
	CapabilityStatusUntested        CapabilityStatus = "untested"
)

// Valid indicates whether the value is a known member of the CapabilityStatus enum.
func (e CapabilityStatus) Valid() bool {
	switch e {
	case CapabilityStatusBlockedByPolicy:
		return true
	case CapabilityStatusDegraded:
		return true
	case CapabilityStatusMissing:
		return true
	case CapabilityStatusOk:
		return true
	case CapabilityStatusUntested:
		return true
	default:
		return false
	}
}

// Defines values for ExistingCodebaseContextBundleSchemaVersion.
const (
	N1 ExistingCodebaseContextBundleSchemaVersion = 1
)

// Valid indicates whether the value is a known member of the ExistingCodebaseContextBundleSchemaVersion enum.
func (e ExistingCodebaseContextBundleSchemaVersion) Valid() bool {
	switch e {
	case N1:
		return true
	default:
		return false
	}
}

// Defines values for HealthResponseAdapters.
const (
	HealthResponseAdaptersDegraded HealthResponseAdapters = "degraded"
	HealthResponseAdaptersMissing  HealthResponseAdapters = "missing"
	HealthResponseAdaptersOk       HealthResponseAdapters = "ok"
	HealthResponseAdaptersUnknown  HealthResponseAdapters = "unknown"
)

// Valid indicates whether the value is a known member of the HealthResponseAdapters enum.
func (e HealthResponseAdapters) Valid() bool {
	switch e {
	case HealthResponseAdaptersDegraded:
		return true
	case HealthResponseAdaptersMissing:
		return true
	case HealthResponseAdaptersOk:
		return true
	case HealthResponseAdaptersUnknown:
		return true
	default:
		return false
	}
}

// Defines values for HealthResponseStatus.
const (
	Degraded HealthResponseStatus = "degraded"
	Draining HealthResponseStatus = "draining"
	Ok       HealthResponseStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthResponseStatus enum.
func (e HealthResponseStatus) Valid() bool {
	switch e {
	case Degraded:
		return true
	case Draining:
		return true
	case Ok:
		return true
	default:
		return false
	}
}

// Defines values for IssuedBearerRole.
const (
	Client IssuedBearerRole = "client"
	Owner  IssuedBearerRole = "owner"
)

// Valid indicates whether the value is a known member of the IssuedBearerRole enum.
func (e IssuedBearerRole) Valid() bool {
	switch e {
	case Client:
		return true
	case Owner:
		return true
	default:
		return false
	}
}

// Defines values for JobStatus.
const (
	JobStatusCanceling       JobStatus = "canceling"
	JobStatusFailed          JobStatus = "failed"
	JobStatusInterrupted     JobStatus = "interrupted"
	JobStatusQueued          JobStatus = "queued"
	JobStatusRunning         JobStatus = "running"
	JobStatusSucceeded       JobStatus = "succeeded"
	JobStatusWaitingApproval JobStatus = "waiting_approval"
)

// Valid indicates whether the value is a known member of the JobStatus enum.
func (e JobStatus) Valid() bool {
	switch e {
	case JobStatusCanceling:
		return true
	case JobStatusFailed:
		return true
	case JobStatusInterrupted:
		return true
	case JobStatusQueued:
		return true
	case JobStatusRunning:
		return true
	case JobStatusSucceeded:
		return true
	case JobStatusWaitingApproval:
		return true
	default:
		return false
	}
}

// Defines values for ManifestSnapshotKind.
const (
	CargoToml     ManifestSnapshotKind = "cargo_toml"
	ComposerJson  ManifestSnapshotKind = "composer_json"
	Gemfile       ManifestSnapshotKind = "gemfile"
	GoMod         ManifestSnapshotKind = "go_mod"
	MixExs        ManifestSnapshotKind = "mix_exs"
	Other         ManifestSnapshotKind = "other"
	PackageJson   ManifestSnapshotKind = "package_json"
	PomXml        ManifestSnapshotKind = "pom_xml"
	PyprojectToml ManifestSnapshotKind = "pyproject_toml"
)

// Valid indicates whether the value is a known member of the ManifestSnapshotKind enum.
func (e ManifestSnapshotKind) Valid() bool {
	switch e {
	case CargoToml:
		return true
	case ComposerJson:
		return true
	case Gemfile:
		return true
	case GoMod:
		return true
	case MixExs:
		return true
	case Other:
		return true
	case PackageJson:
		return true
	case PomXml:
		return true
	case PyprojectToml:
		return true
	default:
		return false
	}
}

// Defines values for MigrationStatePhase.
const (
	MigrationStatePhaseFailed     MigrationStatePhase = "failed"
	MigrationStatePhaseIdle       MigrationStatePhase = "idle"
	MigrationStatePhaseRolledBack MigrationStatePhase = "rolled_back"
	MigrationStatePhaseRunning    MigrationStatePhase = "running"
)

// Valid indicates whether the value is a known member of the MigrationStatePhase enum.
func (e MigrationStatePhase) Valid() bool {
	switch e {
	case MigrationStatePhaseFailed:
		return true
	case MigrationStatePhaseIdle:
		return true
	case MigrationStatePhaseRolledBack:
		return true
	case MigrationStatePhaseRunning:
		return true
	default:
		return false
	}
}

// Defines values for PlanLifecycleState.
const (
	Archived PlanLifecycleState = "archived"
	Draft    PlanLifecycleState = "draft"
	Locked   PlanLifecycleState = "locked"
	Refining PlanLifecycleState = "refining"
)

// Valid indicates whether the value is a known member of the PlanLifecycleState enum.
func (e PlanLifecycleState) Valid() bool {
	switch e {
	case Archived:
		return true
	case Draft:
		return true
	case Locked:
		return true
	case Refining:
		return true
	default:
		return false
	}
}

// Defines values for ProjectAgentContractStatus.
const (
	Missing ProjectAgentContractStatus = "missing"
	Present ProjectAgentContractStatus = "present"
)

// Valid indicates whether the value is a known member of the ProjectAgentContractStatus enum.
func (e ProjectAgentContractStatus) Valid() bool {
	switch e {
	case Missing:
		return true
	case Present:
		return true
	default:
		return false
	}
}

// Defines values for ProjectAgentContractActionId.
const (
	AgentsOpen ProjectAgentContractActionId = "agents.open"
)

// Valid indicates whether the value is a known member of the ProjectAgentContractActionId enum.
func (e ProjectAgentContractActionId) Valid() bool {
	switch e {
	case AgentsOpen:
		return true
	default:
		return false
	}
}

// Defines values for ProjectAgentContractCreateActionId.
const (
	AgentsCreate ProjectAgentContractCreateActionId = "agents.create"
)

// Valid indicates whether the value is a known member of the ProjectAgentContractCreateActionId enum.
func (e ProjectAgentContractCreateActionId) Valid() bool {
	switch e {
	case AgentsCreate:
		return true
	default:
		return false
	}
}

// Defines values for ProjectGate.
const (
	ProjectGateBeadsCreated    ProjectGate = "beads_created"
	ProjectGateBeadsFinalized  ProjectGate = "beads_finalized"
	ProjectGateHardeningReady  ProjectGate = "hardening_ready"
	ProjectGateLaunchReady     ProjectGate = "launch_ready"
	ProjectGatePlanLocked      ProjectGate = "plan_locked"
	ProjectGateProjectImported ProjectGate = "project_imported"
	ProjectGateShipReady       ProjectGate = "ship_ready"
	ProjectGateVpsReady        ProjectGate = "vps_ready"
)

// Valid indicates whether the value is a known member of the ProjectGate enum.
func (e ProjectGate) Valid() bool {
	switch e {
	case ProjectGateBeadsCreated:
		return true
	case ProjectGateBeadsFinalized:
		return true
	case ProjectGateHardeningReady:
		return true
	case ProjectGateLaunchReady:
		return true
	case ProjectGatePlanLocked:
		return true
	case ProjectGateProjectImported:
		return true
	case ProjectGateShipReady:
		return true
	case ProjectGateVpsReady:
		return true
	default:
		return false
	}
}

// Defines values for ProjectLifecycleState.
const (
	ProjectLifecycleStateBeadsCreated    ProjectLifecycleState = "beads_created"
	ProjectLifecycleStateBeadsFinalized  ProjectLifecycleState = "beads_finalized"
	ProjectLifecycleStateCompleted       ProjectLifecycleState = "completed"
	ProjectLifecycleStateHardeningRounds ProjectLifecycleState = "hardening_rounds"
	ProjectLifecycleStateImported        ProjectLifecycleState = "imported"
	ProjectLifecycleStatePlanFinalized   ProjectLifecycleState = "plan_finalized"
	ProjectLifecycleStatePlanning        ProjectLifecycleState = "planning"
	ProjectLifecycleStateQualityGates    ProjectLifecycleState = "quality_gates"
	ProjectLifecycleStateSwarmRunning    ProjectLifecycleState = "swarm_running"
)

// Valid indicates whether the value is a known member of the ProjectLifecycleState enum.
func (e ProjectLifecycleState) Valid() bool {
	switch e {
	case ProjectLifecycleStateBeadsCreated:
		return true
	case ProjectLifecycleStateBeadsFinalized:
		return true
	case ProjectLifecycleStateCompleted:
		return true
	case ProjectLifecycleStateHardeningRounds:
		return true
	case ProjectLifecycleStateImported:
		return true
	case ProjectLifecycleStatePlanFinalized:
		return true
	case ProjectLifecycleStatePlanning:
		return true
	case ProjectLifecycleStateQualityGates:
		return true
	case ProjectLifecycleStateSwarmRunning:
		return true
	default:
		return false
	}
}

// Defines values for ProviderAuthMode.
const (
	ApiToken  ProviderAuthMode = "api-token"
	BasicAuth ProviderAuthMode = "basic-auth"
	Oauth     ProviderAuthMode = "oauth"
)

// Valid indicates whether the value is a known member of the ProviderAuthMode enum.
func (e ProviderAuthMode) Valid() bool {
	switch e {
	case ApiToken:
		return true
	case BasicAuth:
		return true
	case Oauth:
		return true
	default:
		return false
	}
}

// Defines values for ProviderInstanceStatus.
const (
	Destroyed    ProviderInstanceStatus = "destroyed"
	Failed       ProviderInstanceStatus = "failed"
	Provisioning ProviderInstanceStatus = "provisioning"
	Running      ProviderInstanceStatus = "running"
)

// Valid indicates whether the value is a known member of the ProviderInstanceStatus enum.
func (e ProviderInstanceStatus) Valid() bool {
	switch e {
	case Destroyed:
		return true
	case Failed:
		return true
	case Provisioning:
		return true
	case Running:
		return true
	default:
		return false
	}
}

// Defines values for ProviderPluginManifestCapabilities.
const (
	BillingFetch    ProviderPluginManifestCapabilities = "billing.fetch"
	DnsUpdate       ProviderPluginManifestCapabilities = "dns.update"
	VpsCreate       ProviderPluginManifestCapabilities = "vps.create"
	VpsDestroy      ProviderPluginManifestCapabilities = "vps.destroy"
	VpsEstimateCost ProviderPluginManifestCapabilities = "vps.estimate-cost"
	VpsListRegions  ProviderPluginManifestCapabilities = "vps.list-regions"
	VpsListSizes    ProviderPluginManifestCapabilities = "vps.list-sizes"
	VpsResize       ProviderPluginManifestCapabilities = "vps.resize"
	VpsSnapshot     ProviderPluginManifestCapabilities = "vps.snapshot"
)

// Valid indicates whether the value is a known member of the ProviderPluginManifestCapabilities enum.
func (e ProviderPluginManifestCapabilities) Valid() bool {
	switch e {
	case BillingFetch:
		return true
	case DnsUpdate:
		return true
	case VpsCreate:
		return true
	case VpsDestroy:
		return true
	case VpsEstimateCost:
		return true
	case VpsListRegions:
		return true
	case VpsListSizes:
		return true
	case VpsResize:
		return true
	case VpsSnapshot:
		return true
	default:
		return false
	}
}

// Defines values for ProviderSizeTier.
const (
	Minimum     ProviderSizeTier = "minimum"
	Recommended ProviderSizeTier = "recommended"
	Workable    ProviderSizeTier = "workable"
)

// Valid indicates whether the value is a known member of the ProviderSizeTier enum.
func (e ProviderSizeTier) Valid() bool {
	switch e {
	case Minimum:
		return true
	case Recommended:
		return true
	case Workable:
		return true
	default:
		return false
	}
}

// Defines values for ProviderStorageType.
const (
	HDD  ProviderStorageType = "HDD"
	NVMe ProviderStorageType = "NVMe"
	SSD  ProviderStorageType = "SSD"
)

// Valid indicates whether the value is a known member of the ProviderStorageType enum.
func (e ProviderStorageType) Valid() bool {
	switch e {
	case HDD:
		return true
	case NVMe:
		return true
	case SSD:
		return true
	default:
		return false
	}
}

// Defines values for ToolId.
const (
	AgentMail     ToolId = "agent_mail"
	Br            ToolId = "br"
	Bv            ToolId = "bv"
	Caam          ToolId = "caam"
	Casr          ToolId = "casr"
	Caut          ToolId = "caut"
	Dcg           ToolId = "dcg"
	Git           ToolId = "git"
	HealthGeneric ToolId = "health_generic"
	HealthGo      ToolId = "health_go"
	HealthPy      ToolId = "health_py"
	HealthRs      ToolId = "health_rs"
	HealthTs      ToolId = "health_ts"
	Jfp           ToolId = "jfp"
	Jsm           ToolId = "jsm"
	Ntm           ToolId = "ntm"
	Oracle        ToolId = "oracle"
	Pt            ToolId = "pt"
	Rano          ToolId = "rano"
	Rch           ToolId = "rch"
	Ru            ToolId = "ru"
	Sbh           ToolId = "sbh"
	Srp           ToolId = "srp"
	Ubs           ToolId = "ubs"
)

// Valid indicates whether the value is a known member of the ToolId enum.
func (e ToolId) Valid() bool {
	switch e {
	case AgentMail:
		return true
	case Br:
		return true
	case Bv:
		return true
	case Caam:
		return true
	case Casr:
		return true
	case Caut:
		return true
	case Dcg:
		return true
	case Git:
		return true
	case HealthGeneric:
		return true
	case HealthGo:
		return true
	case HealthPy:
		return true
	case HealthRs:
		return true
	case HealthTs:
		return true
	case Jfp:
		return true
	case Jsm:
		return true
	case Ntm:
		return true
	case Oracle:
		return true
	case Pt:
		return true
	case Rano:
		return true
	case Rch:
		return true
	case Ru:
		return true
	case Sbh:
		return true
	case Srp:
		return true
	case Ubs:
		return true
	default:
		return false
	}
}

// Defines values for VersionResponseDaemonChannel.
const (
	Dev     VersionResponseDaemonChannel = "dev"
	Nightly VersionResponseDaemonChannel = "nightly"
	Stable  VersionResponseDaemonChannel = "stable"
)

// Valid indicates whether the value is a known member of the VersionResponseDaemonChannel enum.
func (e VersionResponseDaemonChannel) Valid() bool {
	switch e {
	case Dev:
		return true
	case Nightly:
		return true
	case Stable:
		return true
	default:
		return false
	}
}

// Action One typed action inside an ActionPlan. The `kind` is closed; `target`
// and `args` shapes are per-kind (validated by the daemon against the
// action's published schema in tending-actions.yaml).
type Action struct {
	// Args Per-kind args; opaque at this layer.
	Args *map[string]interface{} `json:"args,omitempty"`

	// IdempotencyKey Stable key used to dedupe repeated executions.
	IdempotencyKey string `json:"idempotencyKey"`

	// Kind Closed enum of allowed tending action types per §8.3.1. Mirrored in
	// `tending-actions.yaml`; the daemon rejects any ActionPlan whose
	// action `kind` is outside this set. Adding a new kind is a deliberate
	// spec bump that lands in both places.
	Kind           ActionKind `json:"kind"`
	Postconditions *[]string  `json:"postconditions,omitempty"`
	Preconditions  *[]string  `json:"preconditions,omitempty"`

	// Target Per-kind target keys (e.g., {agentId}, {branch}).
	Target map[string]interface{} `json:"target"`
}

// ActionKind Closed enum of allowed tending action types per §8.3.1. Mirrored in
// `tending-actions.yaml`; the daemon rejects any ActionPlan whose
// action `kind` is outside this set. Adding a new kind is a deliberate
// spec bump that lands in both places.
type ActionKind string

// ActionPlan What a tending agent emits to mutate state. The daemon (not the
// model) executes; for each action it verifies preconditions, acquires
// locks, evaluates policy + approvals, dry-runs where possible,
// executes through typed RPCs, then re-reads canonical state to
// verify postconditions.
type ActionPlan struct {
	Actions []Action `json:"actions"`

	// EvidenceRefs Opaque IDs into audit / pane logs / reservations / detections.
	EvidenceRefs *[]string `json:"evidenceRefs,omitempty"`

	// JobId Owning tending job ID.
	JobId string `json:"jobId"`

	// RequiresApproval True iff at least one action requires human approval.
	RequiresApproval *bool             `json:"requiresApproval,omitempty"`
	RiskClass        ApprovalRiskClass `json:"riskClass"`

	// RunId Per-execution run ID (ULID).
	RunId string `json:"runId"`

	// SchemaVersion Monotonically increasing schema version for a persisted shape.
	SchemaVersion SchemaVersion `json:"schemaVersion"`

	// Summary One-sentence rationale shown in the Activity panel.
	Summary string `json:"summary"`
}

// Actor Who initiated an action — used in audit + event envelopes.
type Actor struct {
	// DisplayName Optional UI-only label; never used for authorization.
	DisplayName *string `json:"displayName,omitempty"`

	// Id Stable identifier within the actor's namespace.
	Id   *string   `json:"id,omitempty"`
	Kind ActorKind `json:"kind"`
}

// ActorKind defines model for Actor.Kind.
type ActorKind string

// Approval Durable approval record (§5.3). Approvals live in one queue regardless
// of source; the renderer surfaces both Hoopoe-policy and DCG-ingested
// approvals with their `source` rule attached.
type Approval struct {
	AgentId   *string    `json:"agentId,omitempty"`
	BeadId    *string    `json:"beadId,omitempty"`
	DecidedAt *time.Time `json:"decidedAt,omitempty"`

	// DecisionActor Who initiated an action — used in audit + event envelopes.
	DecisionActor *Actor  `json:"decisionActor,omitempty"`
	DecisionNote  *string `json:"decisionNote,omitempty"`

	// EvidenceRefs Opaque IDs pointing into audit log / pane logs / detection records.
	// Resolved client-side via the artifact registry on click.
	EvidenceRefs *[]string  `json:"evidenceRefs,omitempty"`
	ExpiresAt    *time.Time `json:"expiresAt,omitempty"`
	Id           string     `json:"id"`

	// PolicyRule The Hoopoe policy ID or DCG rule ID that required this approval.
	// Surfaced in Diagnostics so the user knows WHY they're being asked.
	PolicyRule *string `json:"policyRule,omitempty"`
	ProjectId  *string `json:"projectId,omitempty"`
	Reason     *string `json:"reason,omitempty"`

	// RequestActor Who initiated an action — used in audit + event envelopes.
	RequestActor Actor `json:"requestActor"`

	// RequestedAction Typed representation of an action the daemon would execute (or has
	// executed). Used by Approval, Job audit, and tending ActionPlans
	// (`packages/schemas/tending-actions.yaml`). The daemon — not the model
	// or renderer — is the executor.
	RequestedAction CommandSpec       `json:"requestedAction"`
	RequestedAt     time.Time         `json:"requestedAt"`
	RiskClass       ApprovalRiskClass `json:"riskClass"`

	// SchemaVersion Monotonically increasing schema version for a persisted shape.
	SchemaVersion SchemaVersion `json:"schemaVersion"`

	// Scope How wide the approval applies. `once` only authorizes the requested
	// execution; `this_bead` applies to identical kind+target within the
	// bead; etc.
	Scope ApprovalScope `json:"scope"`

	// Source Where the approval originated — Hoopoe-policy approvals from the
	// daemon, or DCG verdicts ingested via the agent boundary (§5.3).
	Source  ApprovalSource `json:"source"`
	State   ApprovalState  `json:"state"`
	SwarmId *string        `json:"swarmId,omitempty"`
}

// ApprovalDecisionRequest defines model for ApprovalDecisionRequest.
type ApprovalDecisionRequest struct {
	// DecisionActor Who initiated an action — used in audit + event envelopes.
	DecisionActor Actor   `json:"decisionActor"`
	Note          *string `json:"note,omitempty"`

	// Scope How wide the approval applies. `once` only authorizes the requested
	// execution; `this_bead` applies to identical kind+target within the
	// bead; etc.
	Scope *ApprovalScope `json:"scope,omitempty"`
}

// ApprovalListResponse defines model for ApprovalListResponse.
type ApprovalListResponse struct {
	Items []Approval `json:"items"`
	Page  PageMeta   `json:"page"`
}

// ApprovalRiskClass defines model for ApprovalRiskClass.
type ApprovalRiskClass string

// ApprovalScope How wide the approval applies. `once` only authorizes the requested
// execution; `this_bead` applies to identical kind+target within the
// bead; etc.
type ApprovalScope string

// ApprovalSource Where the approval originated — Hoopoe-policy approvals from the
// daemon, or DCG verdicts ingested via the agent boundary (§5.3).
type ApprovalSource string

// ApprovalState defines model for ApprovalState.
type ApprovalState string

// ArtifactRef Stable handle to a daemon-managed artifact (logs, plan outputs,
// conversion traces, health snapshots, review findings, bootstrap
// logs). Resolved via the artifact registry on demand.
type ArtifactRef struct {
	ContentType *string         `json:"contentType,omitempty"`
	CreatedAt   *time.Time      `json:"createdAt,omitempty"`
	Id          string          `json:"id"`
	Kind        ArtifactRefKind `json:"kind"`
	Sha256      *string         `json:"sha256,omitempty"`
	SizeBytes   *int            `json:"sizeBytes,omitempty"`
}

// ArtifactRefKind defines model for ArtifactRef.Kind.
type ArtifactRefKind string

// Bead One bead from `br`. Edges are cached snapshots; the canonical edge
// truth lives in `.beads/issues.jsonl`.
type Bead struct {
	CreatedAt    *time.Time            `json:"createdAt,omitempty"`
	CreatedBy    *string               `json:"createdBy,omitempty"`
	Dependencies *[]BeadDependencyEdge `json:"dependencies,omitempty"`
	Dependents   *[]BeadDependencyEdge `json:"dependents,omitempty"`
	Description  *string               `json:"description,omitempty"`

	// Id Beads ID, e.g., `hp-r3i`.
	Id        string        `json:"id"`
	IssueType BeadIssueType `json:"issueType"`

	// Priority 0=critical, 1=high, 2=medium, 3=low, 4=backlog.
	Priority BeadPriority `json:"priority"`

	// SchemaVersion Monotonically increasing schema version for a persisted shape.
	SchemaVersion SchemaVersion `json:"schemaVersion"`
	SourceRepo    *string       `json:"sourceRepo,omitempty"`
	Status        BeadStatus    `json:"status"`
	Title         string        `json:"title"`
	UpdatedAt     *time.Time    `json:"updatedAt,omitempty"`
}

// BeadDependencyEdge defines model for BeadDependencyEdge.
type BeadDependencyEdge struct {
	DependencyType BeadDependencyEdgeDependencyType `json:"dependencyType"`

	// Id The other bead ID.
	Id string `json:"id"`

	// Priority 0=critical, 1=high, 2=medium, 3=low, 4=backlog.
	Priority *BeadPriority `json:"priority,omitempty"`
	Status   *BeadStatus   `json:"status,omitempty"`

	// Title Cached title for UI without round-trip.
	Title *string `json:"title,omitempty"`
}

// BeadDependencyEdgeDependencyType defines model for BeadDependencyEdge.DependencyType.
type BeadDependencyEdgeDependencyType string

// BeadIssueType defines model for BeadIssueType.
type BeadIssueType string

// BeadListResponse defines model for BeadListResponse.
type BeadListResponse struct {
	Items []Bead   `json:"items"`
	Page  PageMeta `json:"page"`
}

// BeadPriority 0=critical, 1=high, 2=medium, 3=low, 4=backlog.
type BeadPriority = int

// BeadStatus defines model for BeadStatus.
type BeadStatus string

// BeadSummary Truncated bead summary surfaced to plan candidates so they
// don't re-propose work the swarm has already started or
// finished.
type BeadSummary struct {
	// DependencyCount Number of `blocks` + `soft` dependencies this bead has.
	DependencyCount int `json:"dependencyCount"`

	// Id Stable br bead identifier (e.g., `hp-abc1`).
	Id string `json:"id"`

	// IssueType br issue type (`task` / `bug` / `feature` / `epic` / `question` / `docs`).
	IssueType string `json:"issueType"`

	// Priority P0-P4 (numeric).
	Priority int `json:"priority"`

	// Status br status (`open` / `in_progress` / `closed` / etc.).
	Status string `json:"status"`

	// Title Bead title (truncated to 200 chars).
	Title string `json:"title"`
}

// BootstrapBearerRequest defines model for BootstrapBearerRequest.
type BootstrapBearerRequest struct {
	// InstanceId Human-stable identifier for this client install (e.g.,
	// macOS hardware UUID hash). Recorded on the resulting
	// session for audit and revocation.
	InstanceId string `json:"instanceId"`

	// PairingToken Single-use pairing token issued via `hoopoe pair create`.
	PairingToken string `json:"pairingToken"`
}

// Capability One capability slot inside a `ToolReport`. The map key is the
// capability ID (e.g., `ntm.sessions.list`); the value is this object.
type Capability struct {
	// Fallback Human-readable fallback strategy when status != `ok`. Example:
	// `"tmux capture last"` for `ntm.panes.stream` missing.
	Fallback *string `json:"fallback,omitempty"`

	// Notes Adapter free-text. Surfaced in Diagnostics. Not redacted at the
	// field name (redaction happens at the audit/log boundary, hp-je1p);
	// do not put secrets here.
	Notes *string `json:"notes,omitempty"`

	// Status - `ok` — capability satisfied a contract test.
	// - `degraded` — works via fallback transport / partial output.
	// - `missing` — tool reports the capability is absent.
	// - `blocked-by-policy` — present but disallowed by config.
	// - `untested` — daemon could not probe in this snapshot; renderer
	//   buckets with `missing` (unavailable) but Diagnostics distinguishes
	//   the two.
	Status CapabilityStatus `json:"status"`

	// Transport Transport actually being used for this capability when applicable.
	Transport *CapabilityTransport `json:"transport,omitempty"`
}

// CapabilityTransport Transport actually being used for this capability when applicable.
type CapabilityTransport string

// CapabilityRegistry Authoritative capability snapshot returned by `/v1/capabilities`. The
// `tools` map is keyed by ToolId so renderer code can do
// `registry.tools.git.capabilities['git.push']` in O(1) without scanning
// an array.
type CapabilityRegistry struct {
	// DaemonApiVersion Cross-reference with `/v1/compatibility.daemonApiVersion`.
	DaemonApiVersion string `json:"daemonApiVersion"`

	// FixturesVersion Dominant fixtures tag for the snapshot. Per-tool tags can diverge
	// (each `ToolReport.fixturesVersion` is authoritative for that tool);
	// this is the most-common tag, used for top-level Diagnostics labels.
	FixturesVersion string `json:"fixturesVersion"`

	// SchemaVersion Monotonically increasing schema version for a persisted shape.
	SchemaVersion SchemaVersion `json:"schemaVersion"`

	// SnapshotAt When this composite was assembled (single timestamp across all tools).
	SnapshotAt time.Time `json:"snapshotAt"`

	// Tools Map of ToolId → ToolReport. OpenAPI cannot fully constrain object
	// keys to a closed enum; the daemon enforces `ToolId` membership at
	// serialization. Missing tools are absent from the map (not present
	// with `null`).
	Tools map[string]ToolReport `json:"tools"`
}

// CapabilityStatus - `ok` — capability satisfied a contract test.
//   - `degraded` — works via fallback transport / partial output.
//   - `missing` — tool reports the capability is absent.
//   - `blocked-by-policy` — present but disallowed by config.
//   - `untested` — daemon could not probe in this snapshot; renderer
//     buckets with `missing` (unavailable) but Diagnostics distinguishes
//     the two.
type CapabilityStatus string

// CommandSpec Typed representation of an action the daemon would execute (or has
// executed). Used by Approval, Job audit, and tending ActionPlans
// (`packages/schemas/tending-actions.yaml`). The daemon — not the model
// or renderer — is the executor.
type CommandSpec struct {
	// Args Action-specific args; opaque at this layer.
	Args *map[string]interface{} `json:"args,omitempty"`

	// IdempotencyKey Stable key used to dedupe repeated executions.
	IdempotencyKey *string `json:"idempotencyKey,omitempty"`

	// Kind Action kind. The closed set lives in `tending-actions.yaml`;
	// examples include `git.push_branch`, `agent.send_marching_orders`,
	// `reservation.force_release`, `caam.switch_account`.
	Kind string `json:"kind"`

	// Postconditions Human-readable postconditions verified after execution.
	Postconditions *[]string `json:"postconditions,omitempty"`

	// Preconditions Human-readable preconditions verified before execution.
	Preconditions *[]string `json:"preconditions,omitempty"`

	// Target Action-specific target keys (e.g., `{agentId}`, `{branch}`,
	// `{reservationId}`). Schema is per-action; the daemon validates
	// against the action's published shape.
	Target map[string]interface{} `json:"target"`
}

// CompatibilityReport defines model for CompatibilityReport.
type CompatibilityReport struct {
	// Capabilities Authoritative capability snapshot returned by `/v1/capabilities`. The
	// `tools` map is keyed by ToolId so renderer code can do
	// `registry.tools.git.capabilities['git.push']` in O(1) without scanning
	// an array.
	Capabilities CapabilityRegistry `json:"capabilities"`

	// DaemonApiVersion Semver of the OpenAPI contract this daemon implements.
	DaemonApiVersion string `json:"daemonApiVersion"`

	// EventSchemaVersions Per-channel event schemaVersion (channel → schemaVersion int).
	EventSchemaVersions map[string]int `json:"eventSchemaVersions"`

	// MigrationState Structured daemon-migration state (§10.3). The renderer can pick the
	// coarse `phase` enum for chrome state OR the detailed
	// `schemaVersion`/`appliedAt`/`pending` fields for Diagnostics ("schema 7
	// of 9 applied; pending: foo, bar"). Both stay consistent.
	MigrationState MigrationState `json:"migrationState"`

	// MinDesktopVersion Minimum compatible desktop semver. Older desktops are warned.
	MinDesktopVersion string `json:"minDesktopVersion"`

	// SchemaVersion Monotonically increasing schema version for a persisted shape.
	SchemaVersion SchemaVersion `json:"schemaVersion"`

	// UnsupportedClientWarnings Free-form human-readable warnings (e.g., "desktop 0.0.5 below
	// minimum 0.1.0; please update"). Renderer surfaces these in the
	// top-bar.
	UnsupportedClientWarnings *[]string `json:"unsupportedClientWarnings,omitempty"`
}

// Cursor Opaque pagination cursor. Use the `next` cursor from a list response
// verbatim; do not parse it. Cursors are stable for ≥24h.
type Cursor = string

// EventReplayResponse defines model for EventReplayResponse.
type EventReplayResponse struct {
	Channel string            `json:"channel"`
	Events  []WsEventEnvelope `json:"events"`

	// LatestSequence Highest sequence currently retained for this channel.
	LatestSequence int `json:"latestSequence"`

	// RetentionHorizon Lowest sequence still available via replay. Sequences below this
	// are reachable only via the persisted-log offset on disk.
	RetentionHorizon *int `json:"retentionHorizon,omitempty"`

	// Truncated True iff `limit` capped the result (more events available).
	Truncated *bool `json:"truncated,omitempty"`
}

// ExistingCodebaseContextBundle Existing-codebase context bundle injected into every
// candidate-model prompt when the project's repo is non-empty
// (plan.md §7.1). The shape stays here even before the daemon
// assembly subsystem lands so dependent surfaces (UI artifact
// rail, refinement-round prompts, plan-quality tracker) can
// compile against the contract.
//
// Producer: `apps/daemon/internal/planning/bundle/` (hp-rsly
// residual follow-ups). Consumers: planning pipeline candidate
// prompts, refinement-round serializer, artifact-rail bundle
// viewer.
//
// Cross-references: plan.md §7.1, §5.5, §7.4.1; bead hp-rsly
// residuals.
type ExistingCodebaseContextBundle struct {
	// AgentsMd Single-file capture (README, AGENTS.md, an architecture-doc
	// markdown, etc.). Truncation is explicit so the consumer can
	// surface a user-visible "showing first N bytes" indicator
	// instead of silently dropping content.
	AgentsMd *FileSnapshot `json:"agentsMd,omitempty"`

	// ArchitectureDocs `docs/architecture/*` + `ARCHITECTURE.md` snapshots, capped
	// at 100 KB total per the discovery contract.
	ArchitectureDocs []FileSnapshot `json:"architectureDocs"`

	// CommitSha Git commit SHA (40-hex) the bundle was assembled against.
	// Pinned at bundle-creation time so refinement-round prompts
	// always reference the same source-of-truth even if the
	// working tree advances.
	CommitSha string `json:"commitSha"`

	// ContentHash SHA-256 of the canonicalized bundle contents (lowercase
	// hex). Used by the content-addressable cache so refinement
	// rounds reuse the same bundle without re-assembly.
	ContentHash string `json:"contentHash"`

	// Excluded Project-root-relative paths excluded by size cap, model-
	// context policy, or secret-scan match. Surfaced in the UI
	// "manage what models see" link so the user can audit.
	Excluded []string `json:"excluded"`

	// ExistingBeads Truncated beads from `br list --json --limit 0`.
	ExistingBeads []BeadSummary `json:"existingBeads"`

	// GeneratedAt RFC-3339 timestamp the bundle was produced.
	GeneratedAt time.Time `json:"generatedAt"`

	// HealthHotspots Top 25 hotspots by composite score from the §7.4.1 health
	// pipeline. Capped at 25 by the assembly contract.
	HealthHotspots   []HotspotSummary   `json:"healthHotspots"`
	PackageManifests []ManifestSnapshot `json:"packageManifests"`

	// ProjectId Stable Hoopoe project identifier.
	ProjectId string `json:"projectId"`

	// Readme Single-file capture (README, AGENTS.md, an architecture-doc
	// markdown, etc.). Truncation is explicit so the consumer can
	// surface a user-visible "showing first N bytes" indicator
	// instead of silently dropping content.
	Readme     *FileSnapshot    `json:"readme,omitempty"`
	Redactions []RedactionEntry `json:"redactions"`

	// SchemaVersion Bundle schema version (currently 1).
	SchemaVersion ExistingCodebaseContextBundleSchemaVersion `json:"schemaVersion"`

	// TestLayout Detected test layout so plan candidates don't re-invent
	// runner choice, fixture location, or mock conventions.
	TestLayout *TestLayoutSummary `json:"testLayout,omitempty"`

	// TokenBudget Configured per-prompt token budget. The assembly pipeline
	// truncates lower-priority sections (existing beads → arch
	// docs → manifests) when `tokenEstimate > tokenBudget`, and
	// records every drop in `excluded`.
	TokenBudget int `json:"tokenBudget"`

	// TokenEstimate Estimated token count for the assembled bundle. Used by
	// the truncation order when token budget is exceeded.
	TokenEstimate int `json:"tokenEstimate"`
}

// ExistingCodebaseContextBundleSchemaVersion Bundle schema version (currently 1).
type ExistingCodebaseContextBundleSchemaVersion int

// FileSnapshot Single-file capture (README, AGENTS.md, an architecture-doc
// markdown, etc.). Truncation is explicit so the consumer can
// surface a user-visible "showing first N bytes" indicator
// instead of silently dropping content.
type FileSnapshot struct {
	// ContentB64 Base64-encoded captured bytes.
	ContentB64 string `json:"contentB64"`

	// Path Project-root-relative POSIX path of the captured file.
	Path string `json:"path"`

	// Sha256 SHA-256 of the captured bytes (lowercase hex).
	Sha256 string `json:"sha256"`

	// SizeBytes Size of the (possibly-truncated) captured bytes.
	SizeBytes int `json:"sizeBytes"`

	// TruncatedFromBytes Original file size in bytes when the capture was truncated
	// by the discovery cap. Absent when the file fit under the
	// cap.
	TruncatedFromBytes *int `json:"truncatedFromBytes,omitempty"`
}

// GateCheck One named precondition for a gate. `ok` when satisfied; otherwise
// `detail` explains what's missing in human-readable form.
type GateCheck struct {
	Detail *string `json:"detail,omitempty"`

	// Id Stable check ID, e.g., `agents_md_present`.
	Id string `json:"id"`
	Ok bool   `json:"ok"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	// Adapters Coarse per-tool adapter status (cheap; no full capability check).
	// For authoritative capability gating call `/v1/capabilities`.
	Adapters *map[string]HealthResponseAdapters `json:"adapters,omitempty"`

	// DaemonId Stable daemon instance ID; changes on reinstall.
	DaemonId      string               `json:"daemonId"`
	Status        HealthResponseStatus `json:"status"`
	Time          time.Time            `json:"time"`
	UptimeSeconds *int                 `json:"uptimeSeconds,omitempty"`
}

// HealthResponseAdapters defines model for HealthResponse.Adapters.
type HealthResponseAdapters string

// HealthResponseStatus defines model for HealthResponse.Status.
type HealthResponseStatus string

// HotspotSummary One health hotspot row. The bundle surfaces the top 25 so plan
// candidates flag risk when their first beads land on the
// worst-coverage / highest-complexity files.
type HotspotSummary struct {
	// ChurnScore Recent churn signal (e.g., commit count over the trailing window).
	ChurnScore *float32 `json:"churnScore,omitempty"`

	// ComplexityScore Cyclomatic complexity (or analogous per-language metric).
	ComplexityScore *float32 `json:"complexityScore,omitempty"`

	// CompositeScore Composite ranking that combines complexity, churn, and
	// coverage gap per the §7.4.1 health pipeline. Top-25 ranking
	// uses this field.
	CompositeScore float32 `json:"compositeScore"`

	// Language Detected language (e.g., `typescript`, `python`, `go`).
	Language *string `json:"language,omitempty"`

	// Path Project-root-relative POSIX path of the hotspot file.
	Path string `json:"path"`
}

// IssuedBearer defines model for IssuedBearer.
type IssuedBearer struct {
	BearerToken string           `json:"bearerToken"`
	ExpiresAt   time.Time        `json:"expiresAt"`
	Role        IssuedBearerRole `json:"role"`

	// Sid Session id; durable across daemon restart per hp-b7rx.
	Sid string `json:"sid"`
}

// IssuedBearerRole defines model for IssuedBearer.Role.
type IssuedBearerRole string

// IssuedWSToken defines model for IssuedWSToken.
type IssuedWSToken struct {
	ExpiresAt time.Time `json:"expiresAt"`
	WsToken   string    `json:"wsToken"`
}

// Job One long-running job in the daemon's registry (§2.7). `argvDigest`
// and `envDigest` are blake3 hashes — full argv/env are recorded in the
// artifact registry, redacted on the way out.
type Job struct {
	// Actor Who initiated an action — used in audit + event envelopes.
	Actor *Actor `json:"actor,omitempty"`

	// ApprovalId Set when status is `waiting_approval`.
	ApprovalId *string `json:"approvalId,omitempty"`

	// ArgvDigest Hash of the normalized argv.
	ArgvDigest  *string        `json:"argvDigest,omitempty"`
	Artifacts   *[]ArtifactRef `json:"artifacts,omitempty"`
	CompletedAt *time.Time     `json:"completedAt,omitempty"`
	Cwd         *string        `json:"cwd,omitempty"`
	DurationMs  *int           `json:"durationMs,omitempty"`

	// EnvDigest Hash of the relevant env keys.
	EnvDigest *string `json:"envDigest,omitempty"`
	ExitCode  *int    `json:"exitCode,omitempty"`

	// FailureFingerprint Stable hash of the failure signature (test name, stack frames),
	// used to detect repeated failures across reruns (§2.7).
	FailureFingerprint *string `json:"failureFingerprint,omitempty"`

	// Id Sortable ULID for the job.
	Id        string  `json:"id"`
	ProjectId *string `json:"projectId,omitempty"`

	// SchemaVersion Monotonically increasing schema version for a persisted shape.
	SchemaVersion SchemaVersion `json:"schemaVersion"`
	StartedAt     *time.Time    `json:"startedAt,omitempty"`
	Status        JobStatus     `json:"status"`

	// Type Job kind (e.g., `bootstrap.acfs`, `plan.candidate.generate`,
	// `swarm.spawn`, `health.snapshot`, `tend.swarm`,
	// `build.run`, `test.run`).
	Type string `json:"type"`
}

// JobCancelRequest defines model for JobCancelRequest.
type JobCancelRequest struct {
	// GraceSeconds SIGTERM → SIGKILL escalation window.
	GraceSeconds *int `json:"graceSeconds,omitempty"`

	// Reason Optional human-readable note.
	Reason *string `json:"reason,omitempty"`
}

// JobListResponse defines model for JobListResponse.
type JobListResponse struct {
	Items []Job    `json:"items"`
	Page  PageMeta `json:"page"`
}

// JobStatus defines model for JobStatus.
type JobStatus string

// ManifestSnapshot One package manifest. The bundle assembles all detected
// manifests so plan candidates respect peer-dep / Node-version /
// OS-support constraints already encoded in the codebase.
type ManifestSnapshot struct {
	// Kind Stable manifest kind so the consumer can branch on
	// ecosystem without re-detecting from the path.
	Kind ManifestSnapshotKind `json:"kind"`

	// Parsed Optional pre-parsed structured form. When present the
	// consumer avoids re-parsing; when absent the consumer must
	// parse `raw` itself per ecosystem rules.
	Parsed *map[string]interface{} `json:"parsed,omitempty"`

	// Path Project-root-relative POSIX path of the manifest.
	Path string `json:"path"`

	// Raw Raw manifest contents (as committed).
	Raw string `json:"raw"`
}

// ManifestSnapshotKind Stable manifest kind so the consumer can branch on
// ecosystem without re-detecting from the path.
type ManifestSnapshotKind string

// MigrationState Structured daemon-migration state (§10.3). The renderer can pick the
// coarse `phase` enum for chrome state OR the detailed
// `schemaVersion`/`appliedAt`/`pending` fields for Diagnostics ("schema 7
// of 9 applied; pending: foo, bar"). Both stay consistent.
type MigrationState struct {
	// AppliedAt When the most recent migration step finished.
	AppliedAt time.Time `json:"appliedAt"`

	// Pending Identifiers of unapplied migrations (empty in steady state).
	Pending []string `json:"pending"`

	// Phase Optional coarse phase. Always derivable from the structured fields
	// (`pending == [] → idle` etc.); included so renderer chrome can pick
	// it without computing.
	Phase *MigrationStatePhase `json:"phase,omitempty"`

	// SchemaVersion Currently applied schema version.
	SchemaVersion int `json:"schemaVersion"`
}

// MigrationStatePhase Optional coarse phase. Always derivable from the structured fields
// (`pending == [] → idle` etc.); included so renderer chrome can pick
// it without computing.
type MigrationStatePhase string

// PageMeta defines model for PageMeta.
type PageMeta struct {
	HasMore bool `json:"hasMore"`

	// Next Opaque pagination cursor. Use the `next` cursor from a list response
	// verbatim; do not parse it. Cursors are stable for ≥24h.
	Next *Cursor `json:"next,omitempty"`

	// Total Optional total count; expensive list endpoints omit this.
	Total *int `json:"total,omitempty"`
}

// Plan A planning artifact for a project. Stored as markdown under
// `.hoopoe/plans/<plan-id>/` in the project repo.
type Plan struct {
	// ArtifactsRef Pointer to the artifact bundle (audit log, model raws, traces).
	// Resolves through the daemon's artifact registry.
	ArtifactsRef *string   `json:"artifactsRef,omitempty"`
	CreatedAt    time.Time `json:"createdAt"`
	Id           string    `json:"id"`

	// LatestQuality Composite quality score for a plan (`§7.1`). Each dimension scored
	// 0–10; scoring rubric in `docs/planning/quality-rubric.md` (TBD).
	LatestQuality *PlanQualityScore `json:"latestQuality,omitempty"`
	LockedAt      *time.Time        `json:"lockedAt,omitempty"`
	ProjectId     string            `json:"projectId"`

	// RoundCount Number of refinement rounds completed.
	RoundCount *int `json:"roundCount,omitempty"`

	// SchemaVersion Monotonically increasing schema version for a persisted shape.
	SchemaVersion SchemaVersion      `json:"schemaVersion"`
	State         PlanLifecycleState `json:"state"`
	Title         *string            `json:"title,omitempty"`
}

// PlanLifecycleState defines model for PlanLifecycleState.
type PlanLifecycleState string

// PlanListResponse defines model for PlanListResponse.
type PlanListResponse struct {
	Items []Plan   `json:"items"`
	Page  PageMeta `json:"page"`
}

// PlanQualityScore Composite quality score for a plan (`§7.1`). Each dimension scored
// 0–10; scoring rubric in `docs/planning/quality-rubric.md` (TBD).
type PlanQualityScore struct {
	// Dimensions Per-dimension scores (e.g., `clarity`, `coverage`, `risk_surfacing`).
	Dimensions map[string]float32 `json:"dimensions"`
	Overall    float32            `json:"overall"`
	ScoredAt   time.Time          `json:"scoredAt"`

	// ScorerActor Who initiated an action — used in audit + event envelopes.
	ScorerActor *Actor `json:"scorerActor,omitempty"`
}

// Problem RFC 7807 problem+json. `type` is a daemon-stable URN; `code` is a short
// machine-readable identifier (e.g., `auth.token_expired`,
// `capability.missing`). `instance` is a per-incident URI for support
// deep-links into Diagnostics.
type Problem struct {
	// ApprovalId For `approval.required` problems, the queued approval ID.
	ApprovalId *string `json:"approvalId,omitempty"`

	// Capability For `capability.missing` / `capability.degraded` problems, the
	// capability ID that the operation required.
	Capability *string `json:"capability,omitempty"`

	// Code Machine-readable error code (dot-separated namespace).
	Code string `json:"code"`

	// CorrelationId Opaque correlation handle (matches audit-log entries).
	CorrelationId *string `json:"correlationId,omitempty"`

	// Detail Human-readable explanation; redacted for sensitive fields.
	Detail *string `json:"detail,omitempty"`

	// Instance Per-incident URI; `urn:hoopoe:incident:<id>` is canonical.
	Instance *string `json:"instance,omitempty"`

	// RequestId Echoes `X-Request-Id` if provided.
	RequestId *string `json:"requestId,omitempty"`

	// RetryAfterSeconds Optional hint for `Retry-After`.
	RetryAfterSeconds *int `json:"retryAfterSeconds,omitempty"`

	// Retryable True if the client may safely retry with the same Idempotency-Key.
	Retryable *bool `json:"retryable,omitempty"`

	// Status Mirrors HTTP status.
	Status int `json:"status"`

	// Title Short, human-readable summary.
	Title string `json:"title"`

	// Type Stable problem-type URN (e.g., `urn:hoopoe:auth/token-expired`).
	Type string `json:"type"`
}

// Project One project on this VPS. Lifecycle states + gate invariants are
// canonical (§4); the daemon never lets a stage flip until the gate
// invariants pass.
type Project struct {
	// AgentsContract Per-project agent operating contract status. The daemon surfaces this
	// on import and readiness checks so swarm launch can require agents to
	// reread the project's own instructions before work starts (§7.3, §15).
	AgentsContract *ProjectAgentContract `json:"agentsContract,omitempty"`

	// AgentsManifestPresent Whether AGENTS.md was found on import.
	AgentsManifestPresent *bool `json:"agentsManifestPresent,omitempty"`

	// HoopoeInitialized Whether the project has a populated `.hoopoe/` directory.
	HoopoeInitialized *bool                 `json:"hoopoeInitialized,omitempty"`
	Id                string                `json:"id"`
	ImportedAt        *time.Time            `json:"importedAt,omitempty"`
	LastActivityAt    *time.Time            `json:"lastActivityAt,omitempty"`
	LifecycleState    ProjectLifecycleState `json:"lifecycleState"`

	// Name Human-readable project name.
	Name string         `json:"name"`
	Repo ProjectRepoRef `json:"repo"`

	// SchemaVersion Monotonically increasing schema version for a persisted shape.
	SchemaVersion SchemaVersion `json:"schemaVersion"`

	// Slug URL-safe project slug (used in routes + Activity panel).
	Slug              string `json:"slug"`
	ToolDetectionDone *bool  `json:"toolDetectionDone,omitempty"`

	// VpsId ID of the VpsHost hosting this project.
	VpsId string `json:"vpsId"`
}

// ProjectAgentContract Per-project agent operating contract status. The daemon surfaces this
// on import and readiness checks so swarm launch can require agents to
// reread the project's own instructions before work starts (§7.3, §15).
type ProjectAgentContract struct {
	CreateAction *ProjectAgentContractCreateAction `json:"createAction,omitempty"`

	// DefaultRelativePath Repo-relative path used by the create action when AGENTS.md is missing.
	DefaultRelativePath string                      `json:"defaultRelativePath"`
	OpenAction          *ProjectAgentContractAction `json:"openAction,omitempty"`

	// ReadRequiredBeforeSwarm True when swarm kickoff must instruct agents to reread this contract.
	ReadRequiredBeforeSwarm bool `json:"readRequiredBeforeSwarm"`

	// RelativePath Repo-relative path to the detected AGENTS.md file when present.
	RelativePath *string                    `json:"relativePath,omitempty"`
	Status       ProjectAgentContractStatus `json:"status"`
}

// ProjectAgentContractStatus defines model for ProjectAgentContract.Status.
type ProjectAgentContractStatus string

// ProjectAgentContractAction defines model for ProjectAgentContractAction.
type ProjectAgentContractAction struct {
	Id                 ProjectAgentContractActionId `json:"id"`
	Label              string                       `json:"label"`
	TargetRelativePath string                       `json:"targetRelativePath"`
}

// ProjectAgentContractActionId defines model for ProjectAgentContractAction.Id.
type ProjectAgentContractActionId string

// ProjectAgentContractCreateAction defines model for ProjectAgentContractCreateAction.
type ProjectAgentContractCreateAction struct {
	Id                 ProjectAgentContractCreateActionId `json:"id"`
	Label              string                             `json:"label"`
	TargetRelativePath string                             `json:"targetRelativePath"`

	// Template Editable recommended AGENTS.md template body.
	Template string `json:"template"`

	// TemplateSha256 SHA-256 of the provided template for audit/debug drift checks.
	TemplateSha256 string `json:"templateSha256"`
}

// ProjectAgentContractCreateActionId defines model for ProjectAgentContractCreateAction.Id.
type ProjectAgentContractCreateActionId string

// ProjectCreateRequest Request body for importing an existing project checkout into the daemon
// registry. `Idempotency-Key` is supplied as an HTTP header, not in this
// JSON body.
type ProjectCreateRequest struct {
	// AllowNoLanguageManifest Permit documentation-only repos without package manifests during readiness checks.
	AllowNoLanguageManifest *bool `json:"allowNoLanguageManifest,omitempty"`

	// DesktopMirrorPath Read-only desktop sync mirror path once the desktop clone is created.
	DesktopMirrorPath *string `json:"desktopMirrorPath,omitempty"`

	// Id Optional stable project ID override; omitted values are daemon-generated.
	Id *string `json:"id,omitempty"`

	// Name Optional display name; defaults to the project root basename.
	Name *string `json:"name,omitempty"`

	// RootPath Absolute path to an existing VPS Git checkout.
	RootPath string `json:"rootPath"`

	// Slug Optional route-safe slug; defaults to a slugified name.
	Slug *string `json:"slug,omitempty"`

	// VpsId Optional VPS host ID; defaults to the local daemon host.
	VpsId *string `json:"vpsId,omitempty"`
}

// ProjectGate Named gate per §4.2. Used to key `ProjectReadiness.gates`.
type ProjectGate string

// ProjectLifecycleState defines model for ProjectLifecycleState.
type ProjectLifecycleState string

// ProjectListResponse defines model for ProjectListResponse.
type ProjectListResponse struct {
	Items []Project `json:"items"`
	Page  PageMeta  `json:"page"`
}

// ProjectReadiness Composite readiness snapshot per §4.2. `gates` is keyed in canonical
// order; the desktop renders them as a checklist with the first failing
// gate highlighted.
type ProjectReadiness struct {
	CheckedAt             time.Time              `json:"checkedAt"`
	CurrentLifecycleState *ProjectLifecycleState `json:"currentLifecycleState,omitempty"`
	Gates                 []ProjectReadinessGate `json:"gates"`
	ProjectId             string                 `json:"projectId"`

	// SchemaVersion Monotonically increasing schema version for a persisted shape.
	SchemaVersion SchemaVersion `json:"schemaVersion"`
}

// ProjectReadinessGate defines model for ProjectReadinessGate.
type ProjectReadinessGate struct {
	BlockingCount *int        `json:"blockingCount,omitempty"`
	Checks        []GateCheck `json:"checks"`

	// Gate Named gate per §4.2. Used to key `ProjectReadiness.gates`.
	Gate ProjectGate `json:"gate"`

	// Satisfied True iff all `checks` pass.
	Satisfied bool `json:"satisfied"`
}

// ProjectRepoRef defines model for ProjectRepoRef.
type ProjectRepoRef struct {
	// Branch Default branch the project tracks.
	Branch string `json:"branch"`

	// DesktopMirrorPath Read-only sync mirror path on the desktop (§7.7).
	DesktopMirrorPath *string    `json:"desktopMirrorPath,omitempty"`
	LastFetchedAt     *time.Time `json:"lastFetchedAt,omitempty"`

	// Origin Origin URL of the canonical Git remote (e.g.,
	// `git@github.com:user/repo.git`). NEVER the VPS path; the VPS clone
	// and desktop mirror are sync targets.
	Origin string `json:"origin"`

	// VpsClonePath Working clone path on the VPS (`/data/projects/<project>/`).
	VpsClonePath *string `json:"vpsClonePath,omitempty"`
}

// ProviderAuthMode How the user authenticates with the provider. CAAM holds the
// credential material; Hoopoe never stores provider API tokens
// directly (Guardrail 11 generalised — same principle: third-party
// secrets live in CAAM, not in Hoopoe config).
type ProviderAuthMode string

// ProviderCostEstimate Output of `estimateMonthlyCost`. The `usd` total must match the
// sum of `breakdown[].usd` (renderer asserts this).
type ProviderCostEstimate struct {
	Breakdown []ProviderCostLineItem `json:"breakdown"`

	// CatalogVersion Stable identifier of the catalog snapshot used for this
	// estimate (e.g., `contabo-2026-05-04T00:00`). Lets the wizard
	// invalidate stale estimates when the provider repriced.
	CatalogVersion string `json:"catalogVersion"`

	// Currency Currency the provider actually bills in (e.g., `USD`, `EUR`).
	// Hoopoe always normalizes the displayed value to USD; this
	// field surfaces the original for cost-transparency.
	Currency    *string   `json:"currency,omitempty"`
	EstimatedAt time.Time `json:"estimatedAt"`

	// Usd Total expected monthly cost in USD.
	Usd float32 `json:"usd"`
}

// ProviderCostLineItem defines model for ProviderCostLineItem.
type ProviderCostLineItem struct {
	// Label Cost component (e.g., `compute`, `bandwidth`, `storage`,
	// `datacenter-surcharge`). Plugins should keep this stable across
	// calls so renderer caches don't churn.
	Label string  `json:"label"`
	Usd   float32 `json:"usd"`
}

// ProviderCreateInstanceOpts Inputs to `createInstance`. The SSH public key is the OpenSSH-format
// material the wizard generated (or imported from CAAM); the daemon
// never sees the matching private key.
type ProviderCreateInstanceOpts struct {
	// ImageId Provider-specific image ID (Ubuntu 24.04+ default per §6.5).
	// Defaults to `ProviderPluginManifest.defaultImage` when empty.
	ImageId string `json:"imageId"`

	// Name Human-friendly instance name (e.g., `hoopoe-acfs-2026-05-04`).
	Name string `json:"name"`

	// Region Region ID from `listRegions`.
	Region string `json:"region"`

	// Size Size ID from `listSizes`.
	Size string `json:"size"`

	// SshPubKey OpenSSH-format public key (`ssh-ed25519 ...` or `ssh-rsa ...`).
	// The daemon validates the format before forwarding to the plugin.
	SshPubKey string `json:"sshPubKey"`

	// Tags Optional provider-specific tag map (audit / cost-allocation).
	Tags *map[string]string `json:"tags,omitempty"`
}

// ProviderDestroyResult defines model for ProviderDestroyResult.
type ProviderDestroyResult struct {
	InstanceId string `json:"instanceId"`

	// Notes Optional free-text from the provider (e.g., "instance destroyed,
	// backup retained for 7 days").
	Notes *string `json:"notes,omitempty"`
	Ok    bool    `json:"ok"`
}

// ProviderEstimateCostOpts defines model for ProviderEstimateCostOpts.
type ProviderEstimateCostOpts struct {
	// BandwidthTBExpected Expected monthly bandwidth in TB; defaults to 1 if omitted.
	BandwidthTBExpected *float32 `json:"bandwidthTBExpected,omitempty"`
	Region              string   `json:"region"`
	Size                string   `json:"size"`
}

// ProviderId Stable plugin identifier (e.g., `contabo`, `hetzner`, `do`, `ovh`,
// `linode`). Set by the plugin's `init()` registration; the registry
// rejects duplicate IDs.
type ProviderId = string

// ProviderInstance Result of `createInstance` (and the steady-state shape after
// provisioning succeeds). The IP may be unset while
// `status == provisioning`.
type ProviderInstance struct {
	CreatedAt  time.Time `json:"createdAt"`
	InstanceId string    `json:"instanceId"`

	// Ip IPv4 or IPv6 address; empty until status == running.
	Ip *string `json:"ip,omitempty"`

	// MonthlyUSD Actual billing cost the user will see.
	MonthlyUSD float32 `json:"monthlyUSD"`

	// ProviderInstanceUrl Optional deep-link into the provider dashboard.
	ProviderInstanceUrl *string                `json:"providerInstanceUrl,omitempty"`
	Region              string                 `json:"region"`
	Size                string                 `json:"size"`
	Status              ProviderInstanceStatus `json:"status"`
}

// ProviderInstanceStatus defines model for ProviderInstanceStatus.
type ProviderInstanceStatus string

// ProviderListResponse defines model for ProviderListResponse.
type ProviderListResponse struct {
	Items []ProviderPluginManifest `json:"items"`
}

// ProviderPluginManifest Self-describing manifest a provider plugin returns from its
// `Manifest()` method. Surfaces in the wizard's "choose a provider"
// step and in Diagnostics. Plugins ship as Go packages compiled into
// the daemon binary; v1 ships with Contabo only (`hp-9fo`), with the
// registry open for OVH / Hetzner / DigitalOcean follow-ups.
type ProviderPluginManifest struct {
	// AuthMode How the user authenticates with the provider. CAAM holds the
	// credential material; Hoopoe never stores provider API tokens
	// directly (Guardrail 11 generalised — same principle: third-party
	// secrets live in CAAM, not in Hoopoe config).
	AuthMode ProviderAuthMode `json:"authMode"`

	// Capabilities Coarse capability flags the plugin opts into. Methods absent
	// from this set are treated as unsupported (returning
	// `provider.method_unsupported` in `problem+json`).
	Capabilities []ProviderPluginManifestCapabilities `json:"capabilities"`

	// DefaultImage Provider-specific image ID for "Ubuntu 24.04+ LTS"; used when
	// the user accepts defaults in the create wizard.
	DefaultImage *string `json:"defaultImage,omitempty"`

	// DefaultRegion Region ID to preselect in the wizard.
	DefaultRegion *string `json:"defaultRegion,omitempty"`

	// DisplayName e.g., "Contabo Cloud VPS".
	DisplayName string `json:"displayName"`

	// Homepage Customer-facing landing page; surfaced as the "Visit website" link.
	Homepage *string `json:"homepage,omitempty"`

	// Notes Free-text human-readable note (e.g., "billing in EUR; minimum
	// 30-day commitment"). Surfaced in Diagnostics + the wizard.
	Notes *string `json:"notes,omitempty"`

	// ProviderId Stable plugin identifier (e.g., `contabo`, `hetzner`, `do`, `ovh`,
	// `linode`). Set by the plugin's `init()` registration; the registry
	// rejects duplicate IDs.
	ProviderId ProviderId `json:"providerId"`

	// SchemaVersion Monotonically increasing schema version for a persisted shape.
	SchemaVersion SchemaVersion `json:"schemaVersion"`
}

// ProviderPluginManifestCapabilities defines model for ProviderPluginManifest.Capabilities.
type ProviderPluginManifestCapabilities string

// ProviderRegion One geographic region offered by a provider.
type ProviderRegion struct {
	// Available True when the region is currently provisioning instances.
	Available bool `json:"available"`

	// City Optional city label (e.g., "Frankfurt").
	City *string `json:"city,omitempty"`

	// Country ISO 3166-1 alpha-2 country code (e.g., `DE`).
	Country string `json:"country"`

	// Id Provider-specific region ID (e.g., `eu-central-1`).
	Id string `json:"id"`

	// Name Human-readable label (e.g., "Frankfurt, Germany").
	Name  string  `json:"name"`
	Notes *string `json:"notes,omitempty"`
}

// ProviderRegionListResponse defines model for ProviderRegionListResponse.
type ProviderRegionListResponse struct {
	Items []ProviderRegion `json:"items"`

	// ProviderId Stable plugin identifier (e.g., `contabo`, `hetzner`, `do`, `ovh`,
	// `linode`). Set by the plugin's `init()` registration; the registry
	// rejects duplicate IDs.
	ProviderId ProviderId `json:"providerId"`
}

// ProviderSize One instance size (CPU / RAM / disk / bandwidth + monthly cost).
type ProviderSize struct {
	// BandwidthTB Included monthly bandwidth in TB; 0 means unmetered.
	BandwidthTB int    `json:"bandwidthTB"`
	CpuVCores   int    `json:"cpuVCores"`
	Id          string `json:"id"`

	// MonthlyUSD List price the customer is charged per month.
	MonthlyUSD float32 `json:"monthlyUSD"`
	RamGB      int     `json:"ramGB"`

	// Recommended Convenience flag matching `tier == 'recommended'`. Both are
	// populated for clients that prefer either form.
	Recommended *bool               `json:"recommended,omitempty"`
	StorageGB   int                 `json:"storageGB"`
	StorageType ProviderStorageType `json:"storageType"`

	// Tier Sizing recommendation per §6.2. The wizard renders a "recommended"
	// chip on `recommended` sizes and a "minimum" chip on `minimum`
	// sizes; intermediate sizes are `workable`.
	Tier ProviderSizeTier `json:"tier"`
}

// ProviderSizeListResponse defines model for ProviderSizeListResponse.
type ProviderSizeListResponse struct {
	Items []ProviderSize `json:"items"`

	// ProviderId Stable plugin identifier (e.g., `contabo`, `hetzner`, `do`, `ovh`,
	// `linode`). Set by the plugin's `init()` registration; the registry
	// rejects duplicate IDs.
	ProviderId ProviderId `json:"providerId"`
	RegionId   string     `json:"regionId"`
}

// ProviderSizeTier Sizing recommendation per §6.2. The wizard renders a "recommended"
// chip on `recommended` sizes and a "minimum" chip on `minimum`
// sizes; intermediate sizes are `workable`.
type ProviderSizeTier string

// ProviderStorageType defines model for ProviderStorageType.
type ProviderStorageType string

// RedactionEntry Per-file redaction record. Preserved in the bundle so the user
// can audit "which secrets did the policy drop before models
// saw the bundle".
type RedactionEntry struct {
	// Count Number of redactions applied at this path.
	Count int `json:"count"`

	// Kind Redaction class (e.g., `bearer_token`, `api_key`,
	// `pairing_token`, `ssh_passphrase`, `provider_credential`).
	// Mirrors the redaction-layer surface taxonomy.
	Kind string `json:"kind"`

	// Path Project-root-relative POSIX path where redaction was applied.
	Path string `json:"path"`

	// Surface Optional surface tag (`audit`, `logger`, `model_context`).
	// Defaults to `model_context` for bundle-time redactions.
	Surface *string `json:"surface,omitempty"`
}

// RotateSecretResponse defines model for RotateSecretResponse.
type RotateSecretResponse struct {
	// ReplacementPairingToken One-time replacement owner pairing token. Returned once;
	// the daemon does not retain the plaintext.
	ReplacementPairingToken string `json:"replacementPairingToken"`
	Revoked                 struct {
		// Bearers Number of active bearer sessions revoked by the rotation.
		Bearers int `json:"bearers"`

		// PairingGrants Number of un-consumed pairing tokens revoked.
		PairingGrants int `json:"pairingGrants"`
	} `json:"revoked"`
	RotatedAt time.Time `json:"rotatedAt"`

	// SecretGeneration Monotonic counter of how many times the signing secret has
	// rotated since installation. Bearers signed under prior
	// generations fail with `auth.bearer_invalid_signature`.
	SecretGeneration int `json:"secretGeneration"`
}

// SchemaVersion Monotonically increasing schema version for a persisted shape.
type SchemaVersion = int

// SessionRevokeRequest defines model for SessionRevokeRequest.
type SessionRevokeRequest struct {
	Sid string `json:"sid"`
}

// SessionRevokeResponse defines model for SessionRevokeResponse.
type SessionRevokeResponse struct {
	// Revoked False iff the sid was already revoked or unknown — the
	// handler is idempotent over `sid`.
	Revoked bool   `json:"revoked"`
	Sid     string `json:"sid"`
}

// TestLayoutSummary Detected test layout so plan candidates don't re-invent
// runner choice, fixture location, or mock conventions.
type TestLayoutSummary struct {
	// CoverageConfig Path of the detected coverage config when present (e.g.,
	// `vitest.config.ts`, `pyproject.toml`'s `[tool.coverage]`
	// block, `.codecov.yml`).
	CoverageConfig *string `json:"coverageConfig,omitempty"`

	// FixtureConventions Detected fixture-data conventions (e.g., `__fixtures__/`,
	// `testdata/`, `tests/fixtures/`).
	FixtureConventions []string `json:"fixtureConventions"`

	// Runner Detected primary test runner (e.g., `vitest`, `bun:test`,
	// `pytest`, `go test`, `cargo test`). `unknown` when no
	// runner could be detected with confidence.
	Runner string `json:"runner"`

	// TestFilePatterns Globs the runner picks up by convention (e.g.,
	// `**/*.test.ts`, `tests/**/test_*.py`).
	TestFilePatterns []string `json:"testFilePatterns"`
}

// ToolId Closed enum of tools the capability registry knows about. New
// ecosystem health probes (e.g., `health_zig`) require an explicit
// spec bump per §10.3; the daemon-side checker uses a `health_*`
// prefix-match for forward-compat input validation.
type ToolId string

// ToolReport One tool's slice of the capability registry. Compose into
// `CapabilityRegistry.tools` keyed by ToolId.
type ToolReport struct {
	// Capabilities Map of capability ID → capability slot. Capability IDs are dotted
	// namespaces (e.g., `ntm.sessions.list`, `bv.robot.triage`). The full
	// list of recognised capability IDs is owned by hp-r33.
	Capabilities map[string]Capability `json:"capabilities"`

	// FixturesVersion Phase 0 fixture tag this registry was validated against.
	FixturesVersion string    `json:"fixturesVersion"`
	LastCheckedAt   time.Time `json:"lastCheckedAt"`

	// Source How capabilities were detected. Examples: `"ntm serve"`,
	// `"--robot-* JSON"`, `"CLI"`, `"fixture"`.
	Source string `json:"source"`

	// Tool Closed enum of tools the capability registry knows about. New
	// ecosystem health probes (e.g., `health_zig`) require an explicit
	// spec bump per §10.3; the daemon-side checker uses a `health_*`
	// prefix-match for forward-compat input validation.
	Tool ToolId `json:"tool"`

	// Version Semver (or vendor version string) of the tool. Empty if unknown.
	Version string `json:"version"`
}

// VersionResponse defines model for VersionResponse.
type VersionResponse struct {
	Daemon struct {
		AttestationUri *string                       `json:"attestationUri,omitempty"`
		BuildTime      *time.Time                    `json:"buildTime,omitempty"`
		Channel        *VersionResponseDaemonChannel `json:"channel,omitempty"`

		// Checksum Distribution checksum (matches release manifest)
		Checksum *string `json:"checksum,omitempty"`

		// Commit Git SHA of the build
		Commit *string `json:"commit,omitempty"`

		// SbomDigest SBOM digest recorded at install time (§11)
		SbomDigest *string `json:"sbomDigest,omitempty"`

		// SigningIdentity Signer identity (e.g., "Hoopoe v1 Release Key")
		SigningIdentity *string `json:"signingIdentity,omitempty"`

		// Version Semver of the daemon binary
		Version string `json:"version"`
	} `json:"daemon"`

	// SchemaVersion Monotonically increasing schema version for a persisted shape.
	SchemaVersion SchemaVersion `json:"schemaVersion"`
}

// VersionResponseDaemonChannel defines model for VersionResponse.Daemon.Channel.
type VersionResponseDaemonChannel string

// WsEventEnvelope Daemon → client envelope for every project / swarm / activity event.
// `sequence` is monotonic per `channel`; clients persist the last seen
// and pass it back on reconnect for replay.
type WsEventEnvelope struct {
	// Actor Who initiated an action — used in audit + event envelopes.
	Actor *Actor `json:"actor,omitempty"`

	// CausationId ID of the command/action that caused this event.
	CausationId *string `json:"causationId,omitempty"`

	// Channel e.g., `project:proj_01`, `swarm:sw_01`.
	Channel string `json:"channel"`

	// CorrelationId Cross-event handle (e.g., swarm session ID).
	CorrelationId *string `json:"correlationId,omitempty"`

	// Data Event-type-specific payload. Schema per `type`; consumers should
	// switch on `type` and validate against the published per-type schema.
	// Unknown types should not fail-closed (forward-compat).
	Data interface{} `json:"data,omitempty"`

	// EventId ULID for the event.
	EventId string `json:"eventId"`

	// SchemaVersion Monotonically increasing schema version for a persisted shape.
	SchemaVersion SchemaVersion `json:"schemaVersion"`

	// Sequence Monotonic per channel.
	Sequence int       `json:"sequence"`
	Time     time.Time `json:"time"`

	// Type Channel-scoped event type (e.g., `bead.changed`, `agent.idle`,
	// `job.status.changed`). The daemon publishes the per-channel
	// registry; clients tolerate unknown types (forward-compat).
	Type string `json:"type"`
}

// IdempotencyKey defines model for IdempotencyKey.
type IdempotencyKey = string

// ProjectIdPath defines model for ProjectIdPath.
type ProjectIdPath = string

// bearerAuthContextKey is the context key for bearerAuth security scheme
type bearerAuthContextKey string

// BootstrapBearerParams defines parameters for BootstrapBearer.
type BootstrapBearerParams struct {
	// IdempotencyKey Stable client-generated key (ULID/UUID) for safe retries. The daemon
	// dedupes by key within a sliding window (default 24h) and replays the
	// original status + body. Required on retryable writes; clients that omit
	// it on a write that turns out to be retryable will receive a
	// `precondition-failed` problem on the second attempt.
	IdempotencyKey *IdempotencyKey `json:"Idempotency-Key,omitempty"`
}

// RotateAuthSecretParams defines parameters for RotateAuthSecret.
type RotateAuthSecretParams struct {
	// IdempotencyKey Stable client-generated key (ULID/UUID) for safe retries. The daemon
	// dedupes by key within a sliding window (default 24h) and replays the
	// original status + body. Required on retryable writes; clients that omit
	// it on a write that turns out to be retryable will receive a
	// `precondition-failed` problem on the second attempt.
	IdempotencyKey *IdempotencyKey `json:"Idempotency-Key,omitempty"`
}

// RevokeSessionParams defines parameters for RevokeSession.
type RevokeSessionParams struct {
	// IdempotencyKey Stable client-generated key (ULID/UUID) for safe retries. The daemon
	// dedupes by key within a sliding window (default 24h) and replays the
	// original status + body. Required on retryable writes; clients that omit
	// it on a write that turns out to be retryable will receive a
	// `precondition-failed` problem on the second attempt.
	IdempotencyKey *IdempotencyKey `json:"Idempotency-Key,omitempty"`
}

// IssueWSTokenParams defines parameters for IssueWSToken.
type IssueWSTokenParams struct {
	// IdempotencyKey Stable client-generated key (ULID/UUID) for safe retries. The daemon
	// dedupes by key within a sliding window (default 24h) and replays the
	// original status + body. Required on retryable writes; clients that omit
	// it on a write that turns out to be retryable will receive a
	// `precondition-failed` problem on the second attempt.
	IdempotencyKey *IdempotencyKey `json:"Idempotency-Key,omitempty"`
}

// GetCapabilitiesParams defines parameters for GetCapabilities.
type GetCapabilitiesParams struct {
	// Tool Filter to a single tool (e.g., `ntm`, `br`, `bv`).
	Tool *string `form:"tool,omitempty" json:"tool,omitempty"`
}

// ReplayEventsParams defines parameters for ReplayEvents.
type ReplayEventsParams struct {
	// Channel Channel selector (e.g., `project:proj_01`).
	Channel string `form:"channel" json:"channel"`

	// SinceSequence Last-known sequence number; replay returns sequence > this.
	SinceSequence int  `form:"sinceSequence" json:"sinceSequence"`
	Limit         *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// StreamEventsSSEParams defines parameters for StreamEventsSSE.
type StreamEventsSSEParams struct {
	// Channels Comma-separated channel selectors.
	Channels string `form:"channels" json:"channels"`

	// Cursors Optional URL-encoded JSON map of `{channel: lastSequence}`
	// for replay-on-connect.
	Cursors *string `form:"cursors,omitempty" json:"cursors,omitempty"`
}

// StreamEventsWSParams defines parameters for StreamEventsWS.
type StreamEventsWSParams struct {
	// WsToken 5-minute WS token from `/v1/events/ws-token`.
	WsToken string `form:"wsToken" json:"wsToken"`
}

// ListJobsParams defines parameters for ListJobs.
type ListJobsParams struct {
	// Status Filter by job status (multi-value).
	Status    *[]JobStatus `form:"status,omitempty" json:"status,omitempty"`
	ProjectId *string      `form:"projectId,omitempty" json:"projectId,omitempty"`
	Cursor    *Cursor      `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit     *int         `form:"limit,omitempty" json:"limit,omitempty"`
}

// CancelJobParams defines parameters for CancelJob.
type CancelJobParams struct {
	// IdempotencyKey Stable client-generated key (ULID/UUID) for safe retries. The daemon
	// dedupes by key within a sliding window (default 24h) and replays the
	// original status + body. Required on retryable writes; clients that omit
	// it on a write that turns out to be retryable will receive a
	// `precondition-failed` problem on the second attempt.
	IdempotencyKey *IdempotencyKey `json:"Idempotency-Key,omitempty"`
}

// ListProjectsParams defines parameters for ListProjects.
type ListProjectsParams struct {
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *int    `form:"limit,omitempty" json:"limit,omitempty"`
}

// CreateProjectParams defines parameters for CreateProject.
type CreateProjectParams struct {
	// IdempotencyKey Stable client-generated key (ULID/UUID) for safe retries. The daemon
	// dedupes by key within a sliding window (default 24h) and replays the
	// original status + body. Required on retryable writes; clients that omit
	// it on a write that turns out to be retryable will receive a
	// `precondition-failed` problem on the second attempt.
	IdempotencyKey *IdempotencyKey `json:"Idempotency-Key,omitempty"`
}

// ListApprovalsParams defines parameters for ListApprovals.
type ListApprovalsParams struct {
	// State Filter by approval state.
	State  *[]ApprovalState `form:"state,omitempty" json:"state,omitempty"`
	Cursor *Cursor          `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *int             `form:"limit,omitempty" json:"limit,omitempty"`
}

// ApproveApprovalParams defines parameters for ApproveApproval.
type ApproveApprovalParams struct {
	// IdempotencyKey Stable client-generated key (ULID/UUID) for safe retries. The daemon
	// dedupes by key within a sliding window (default 24h) and replays the
	// original status + body. Required on retryable writes; clients that omit
	// it on a write that turns out to be retryable will receive a
	// `precondition-failed` problem on the second attempt.
	IdempotencyKey *IdempotencyKey `json:"Idempotency-Key,omitempty"`
}

// DenyApprovalParams defines parameters for DenyApproval.
type DenyApprovalParams struct {
	// IdempotencyKey Stable client-generated key (ULID/UUID) for safe retries. The daemon
	// dedupes by key within a sliding window (default 24h) and replays the
	// original status + body. Required on retryable writes; clients that omit
	// it on a write that turns out to be retryable will receive a
	// `precondition-failed` problem on the second attempt.
	IdempotencyKey *IdempotencyKey `json:"Idempotency-Key,omitempty"`
}

// ListBeadsParams defines parameters for ListBeads.
type ListBeadsParams struct {
	// Status Filter by bead status (multi-value supported).
	Status *[]BeadStatus `form:"status,omitempty" json:"status,omitempty"`
	Cursor *Cursor       `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *int          `form:"limit,omitempty" json:"limit,omitempty"`
}

// ListPlansParams defines parameters for ListPlans.
type ListPlansParams struct {
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *int    `form:"limit,omitempty" json:"limit,omitempty"`
}

// SubmitActionPlanParams defines parameters for SubmitActionPlan.
type SubmitActionPlanParams struct {
	// IdempotencyKey Stable client-generated key (ULID/UUID) for safe retries. The daemon
	// dedupes by key within a sliding window (default 24h) and replays the
	// original status + body. Required on retryable writes; clients that omit
	// it on a write that turns out to be retryable will receive a
	// `precondition-failed` problem on the second attempt.
	IdempotencyKey *IdempotencyKey `json:"Idempotency-Key,omitempty"`
}

// CreateProviderInstanceParams defines parameters for CreateProviderInstance.
type CreateProviderInstanceParams struct {
	// IdempotencyKey Stable client-generated key (ULID/UUID) for safe retries. The daemon
	// dedupes by key within a sliding window (default 24h) and replays the
	// original status + body. Required on retryable writes; clients that omit
	// it on a write that turns out to be retryable will receive a
	// `precondition-failed` problem on the second attempt.
	IdempotencyKey *IdempotencyKey `json:"Idempotency-Key,omitempty"`
}

// DestroyProviderInstanceParams defines parameters for DestroyProviderInstance.
type DestroyProviderInstanceParams struct {
	// IdempotencyKey Stable client-generated key (ULID/UUID) for safe retries. The daemon
	// dedupes by key within a sliding window (default 24h) and replays the
	// original status + body. Required on retryable writes; clients that omit
	// it on a write that turns out to be retryable will receive a
	// `precondition-failed` problem on the second attempt.
	IdempotencyKey *IdempotencyKey `json:"Idempotency-Key,omitempty"`
}

// BootstrapBearerJSONRequestBody defines body for BootstrapBearer for application/json ContentType.
type BootstrapBearerJSONRequestBody = BootstrapBearerRequest

// RevokeSessionJSONRequestBody defines body for RevokeSession for application/json ContentType.
type RevokeSessionJSONRequestBody = SessionRevokeRequest

// CancelJobJSONRequestBody defines body for CancelJob for application/json ContentType.
type CancelJobJSONRequestBody = JobCancelRequest

// CreateProjectJSONRequestBody defines body for CreateProject for application/json ContentType.
type CreateProjectJSONRequestBody = ProjectCreateRequest

// ApproveApprovalJSONRequestBody defines body for ApproveApproval for application/json ContentType.
type ApproveApprovalJSONRequestBody = ApprovalDecisionRequest

// DenyApprovalJSONRequestBody defines body for DenyApproval for application/json ContentType.
type DenyApprovalJSONRequestBody = ApprovalDecisionRequest

// SubmitActionPlanJSONRequestBody defines body for SubmitActionPlan for application/json ContentType.
type SubmitActionPlanJSONRequestBody = ActionPlan

// EstimateProviderMonthlyCostJSONRequestBody defines body for EstimateProviderMonthlyCost for application/json ContentType.
type EstimateProviderMonthlyCostJSONRequestBody = ProviderEstimateCostOpts

// CreateProviderInstanceJSONRequestBody defines body for CreateProviderInstance for application/json ContentType.
type CreateProviderInstanceJSONRequestBody = ProviderCreateInstanceOpts
