package metrics

func DefaultTargets() []Target {
	return []Target{
		{
			ID:          "desktop_reconnect_after_wake",
			Area:        "Desktop reconnect after laptop wake",
			Metric:      MetricDesktopReconnectAfterWakeMS,
			Source:      "desktop",
			Description: "p95 under 10s after network returns",
			Comparator:  ComparatorP95LessEqual,
			Threshold:   10000,
			Unit:        UnitMilliseconds,
		},
		{
			ID:          "event_replay_after_disconnect",
			Area:        "Event replay after 10-min disconnect",
			Metric:      MetricEventReplayAfterDisconnectMS,
			Source:      "daemon",
			Description: "p95 under 5s for normal channels with no lost state",
			Comparator:  ComparatorP95LessEqual,
			Threshold:   5000,
			Unit:        UnitMilliseconds,
		},
		{
			ID:          "activity_event_display_latency",
			Area:        "Activity event display latency",
			Metric:      MetricActivityEventDisplayMS,
			Source:      "desktop",
			Description: "p95 under 1s excluding terminal chunks",
			Comparator:  ComparatorP95LessEqual,
			Threshold:   1000,
			Unit:        UnitMilliseconds,
		},
		{
			ID:          "terminal_stream_attach",
			Area:        "Terminal stream attach",
			Metric:      MetricTerminalStreamAttachMS,
			Source:      "daemon",
			Description: "latest ring visible under 2s",
			Comparator:  ComparatorP95LessEqual,
			Threshold:   2000,
			Unit:        UnitMilliseconds,
		},
		{
			ID:          "local_file_open_cached",
			Area:        "Local file open from clone",
			Metric:      MetricLocalFileOpenCachedMS,
			Source:      "desktop",
			Description: "p95 under 150ms for cached blobs",
			Comparator:  ComparatorP95LessEqual,
			Threshold:   150,
			Unit:        UnitMilliseconds,
		},
		{
			ID:          "bead_kanban_load",
			Area:        "Bead Kanban load",
			Metric:      MetricBeadKanbanLoadMS,
			Source:      "desktop",
			Description: "p95 under 1s for 1,000 beads",
			Comparator:  ComparatorP95LessEqual,
			Threshold:   1000,
			Unit:        UnitMilliseconds,
		},
		{
			ID:          "dag_visible_nodes",
			Area:        "DAG usable",
			Metric:      MetricDAGVisibleNodes,
			Source:      "desktop",
			Description: "500 visible nodes before clustering",
			Comparator:  ComparatorLatestGreaterEq,
			Threshold:   500,
			Unit:        UnitNodes,
		},
		{
			ID:          "job_cancellation_orphans",
			Area:        "Job cancellation",
			Metric:      MetricJobCancellationOrphans,
			Source:      "daemon",
			Description: "no orphan child process groups after cancel test",
			Comparator:  ComparatorLatestEqual,
			Threshold:   0,
			Unit:        UnitCount,
		},
	}
}
